### ISSUE TITLE
Case.build no longer remakes the EXEROOT and RUNDIR

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#1035]
In pervious version of cime, one could "rm -rf" the entire "$CIME_OUTPUT_ROOT/$CASE" directory and "case.build" would re-create that and the bld and run subdirs  before building.

In the most recent version, if I remove the $CIME_OUTPUT_ROOT/$CASE dir and then try to run "case.build", I get an error:

```
blogin3[42]: ./case.build
calling build.case_build with caseroot=/lcrc/group/earthscience/jacob/cimeESMCI/scripts/Xcase
Building case in directory /lcrc/group/earthscience/jacob/cimeESMCI/scripts/Xcase
sharedlib_only is False
model_only is False
Generating component namelists as part of build
Creating component namelists
   Calling xatm buildnml
Traceback (most recent call last):
  File "./case.build", line 118, in <module>
    _main_func(__doc__)
  File "./case.build", line 110, in _main_func
    model_only=model_only)
  File "/lcrc/group/earthscience/jacob/cimeESMCI/scripts/Tools/../../utils/python/CIME/build.py", line 284, in case_build
    complist, ninst_build, smp_value, model_only)
  File "/lcrc/group/earthscience/jacob/cimeESMCI/scripts/Tools/../../utils/python/CIME/build.py", line 412, in build_checks
    create_namelists(case)
  File "/lcrc/group/earthscience/jacob/cimeESMCI/scripts/Tools/../../utils/python/CIME/preview_namelists.py", line 82, in create_namelists
    mod.buildnml(case, caseroot, compname)
  File "/lcrc/group/earthscience/jacob/cimeESMCI/components/xcpl_comps/xatm/cime_config/buildnml", line 19, in buildnml
    build_xcpl_nml(case, caseroot, compname)
  File "/lcrc/group/earthscience/jacob/cimeESMCI/scripts/Tools/../../utils/python/CIME/buildnml.py", line 85, in build_xcpl_nml
    with open(filename, 'w') as infile:
IOError: [Errno 2] No such file or directory: '/lcrc/project/ACME/jacob/acme_scratch/Xcase/run/xatm_in'
Exit 1
```

If that change is intentional, case.build should give a more helpful error message.

**Comment by rljacob** [comment]
I reran case.setup and then case.build worked.

**Comment by jgfouca** [comment]
Either needs a better error statement or needs to make dirs.
