### ISSUE TITLE
ERP test broken

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#1066]
With a fresh checkout of master, tried:
`./create_test ERP.f19_f19.A.hobart_nag --test-root /scratch/cluster/goldy/ERPtestA --output-root /scratch/cluster/goldy/ERPtestA --test-id testA`
Run failed with the test.o file showing:
```
Found difference in RUN_WITH_SUBMIT: case: True original value False
 Use option --force to run the test with this value or --reset to reset to original
Successfully cleaned batch script case.run
Checking file env_case
Checking file env_mach_pes
File /scratch/cluster/goldy/ERPtestA/ERP.f19_f19.A.hobart_nag.testA/LockedFiles/env_mach_pes.ERP1.xml has been modified
  found difference in TOTALPES : case 12 locked 24
Exception during run:
ERROR: Invoke case.setup --reset 
Traceback (most recent call last):
  File "/scratch/cluster/goldy/foocime/scripts/Tools/../../utils/python/CIME/SystemTests/system_tests_common.py", line 137, in run
    self.run_phase()
  File "/scratch/cluster/goldy/foocime/scripts/Tools/../../utils/python/CIME/SystemTests/erp.py", line 116, in run_phase
    case_setup(self._case, test_mode=True, reset=True)
  File "/scratch/cluster/goldy/foocime/scripts/Tools/../../utils/python/CIME/case_setup.py", line 247, in case_setup
    _case_setup_impl(case, caseroot, clean=clean, test_mode=test_mode, reset=reset)
  File "/scratch/cluster/goldy/foocime/scripts/Tools/../../utils/python/CIME/case_setup.py", line 149, in _case_setup_impl
    check_lockedfiles()
  File "/scratch/cluster/goldy/foocime/scripts/Tools/../../utils/python/CIME/check_lockedfiles.py", line 115, in check_lockedfiles
    expect(False, "Invoke case.setup --reset ")
  File "/scratch/cluster/goldy/foocime/scripts/Tools/../../utils/python/CIME/utils.py", line 26, in expect
    raise exc_type("ERROR: %s" % error_msg)
SystemExit: ERROR: Invoke case.setup --reset 

```

**Comment by gold2718** [comment]
This test works in cime5.2.0-alpha.20

**Comment by jedwards4b** [comment]
I've got a fix for this, there are several other tests failing as well (ERS, ERR) - the regression tests were missing these failures.

**Comment by gold2718** [comment]
A bisect says that the bad commit is:
`[20f56149bc607be1447b7213e5a1dc7319a9b6a1] Lock env_mach.xml file`
Will the fix branch from that point as documented in the [Repository workflow](https://github.com/ESMCI/cime/wiki/Repository-workflow)?

> Bug fixes should start from the earliest commit that introduced the bug: git branch username/component/bug-fix commit-with-bug.
