### ISSUE TITLE
Invalid literal error doing namelist compare

### ISSUE THREAD

**Issue by fischer-ncar** [ESMCI/cime#1115]
I get the following error message when doing certain namelist comparisons. 

    2017-02-06 21:02:09: Exception during namelist operations:
    invalid literal for int() with base 10: "'pom_a1 = 1.4"
    Traceback (most recent call last):
      File "/glade/u/home/fischer/code/cesm2_0_alpha06c/cime/scripts/Tools/../../utils/python/CIME/case_cmpgen_namelists.py", line 123, in case_cmpgen_namelists
        success, output = _do_full_nl_comp(case, test_name, compare_name, baseline_root)
      File "/glade/u/home/fischer/code/cesm2_0_alpha06c/cime/scripts/Tools/../../utils/python/CIME/case_cmpgen_namelists.py", line 44, in _do_full_nl_comp
        if is_namelist_file(item):
      File "/glade/u/home/fischer/code/cesm2_0_alpha06c/cime/scripts/Tools/../../utils/python/CIME/compare_namelists.py", line 538, in is_namelist_file
        compare_namelist_files(file_path, file_path)
      File "/glade/u/home/fischer/code/cesm2_0_alpha06c/cime/scripts/Tools/../../utils/python/CIME/compare_namelists.py", line 528, in compare_namelist_files
        gold_namelists = _parse_namelists(open(gold_file, "r").readlines(), gold_file)
      File "/glade/u/home/fischer/code/cesm2_0_alpha06c/cime/scripts/Tools/../../utils/python/CIME/compare_namelists.py", line 239, in _parse_namelists
        real_value = _interpret_value(value_str, filename)
      File "/glade/u/home/fischer/code/cesm2_0_alpha06c/cime/scripts/Tools/../../utils/python/CIME/compare_namelists.py", line 78, in _interpret_value
        new_tokens.extend([sub_tokens[1]] * int(sub_tokens[0]))
    ValueError: invalid literal for int() with base 10: "'pom_a1 = 1.4" 
 

This is the namelist that's causing the error.

&fire_emis_nl
  fire_emis_factors_file = '/glade/p/cesmdata/cseg/inputdata/lnd/clm2/firedata/fire_emis_factors_c140116.nc'
  fire_emis_specifier = 'bc_a1 = BC', 'pom_a1 = 1.4*OC', 'SO2 = SO2'
/
&megan_emis_nl
  megan_factors_file = '/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/trop_mozart/emis/megan21_emis_factors_78pft_c20161108.nc'
  megan_specifier = 'ISOP = isoprene',
      'C10H16 = pinene_a + carene_3 + thujene_a', 'CH3OH = methanol',
      'C2H5OH = ethanol', 'CH2O = formaldehyde', 'CH3CHO = acetaldehyde',
      'CH3COOH = acetic_acid', 'CH3COCH3 = acetone'
/

**Comment by mvertens** [comment]
Could you please also show what the previous namelist was - that way we
know what is triggering the compare fail.

**Comment by fischer-ncar** [comment]
The previous namelist was identical.

**Comment by mvertens** [comment]
To clarify - you have two identical namelists and the namelist compare dies
in comparing them?

**Comment by fischer-ncar** [comment]
That is correct.  The two namelist files are identical.

**Comment by cacraigucar** [comment]
This might be related to #1103   In both cases, it appears that the tool(s) might be trying to do actual arithmetic on namelist values which are strings.

**Comment by mvertens** [comment]
@foucar - this is a critical issue for us since we cannot do baseline compares without this fix. Is it possible for you to take this on?

**Comment by jgfouca** [comment]
@mvertens, yes looking at it now.

**Comment by mvertens** [comment]
Thank you so much!!!
