### ISSUE TITLE
Bug when resetting RUNDIR

### ISSUE THREAD

**Issue by cacraigucar** [ESMCI/cime#1189]
From Jim Benedict:

There appears to be a bug when setting RUNDIR within env_run.xml in CESM2.  I first encountered this error in cesm2_0_beta03 (it may have existed in earlier tags), and I also see it in cesm2_0_beta05.  It occurs when I try to create an aquaplanet case, but I also see it when I try to make a simple F compset run with cesm2_0_beta05.  When RUNDIR is not modified, no errors occur.

The screen output below shows the error message when RUNDIR in env_run.xml is user-specified (and after ./preview_namelists is attempted).  The case directory for this run is:
/glade/u/home/benedict/ys/model/cesm/cesm2_0_beta05/cases/F_RUNDIRtest

~~~  Error message  ~~~
120 yslogin3% ./preview_namelists
Creating component namelists
   Calling cam buildnml
Traceback (most recent call last):
  File "./preview_namelists", line 64, in <module>
    _main_func(__doc__)
  File "./preview_namelists", line 61, in _main_func
    create_namelists(case)
  File "/glade/u/home/benedict/ys/model/cesm/cesm2_0_beta05/cime/scripts/Tools/../../utils/python/CIME/preview_namelists.py", line 82, in create_namelists
    mod.buildnml(case, caseroot, compname)
  File "/glade/u/home/benedict/ys/model/cesm/cesm2_0_beta05/components/cam/cime_config/buildnml", line 189, in buildnml
    shutil.copy(file1,file2)
  File "/glade/apps/opt/python/2.7.7/gnu-westmere/4.8.2/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/glade/apps/opt/python/2.7.7/gnu-westmere/4.8.2/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/glade/p/umia0018/F_RUNDIRtest/run/drv_flds_in’

From Jim Edwards:
 Yes, it is a bug - can you open a cime issue?   I think that the workaround is to create the directory after you run the 
xmlchange command but before anything else.

**Comment by gold2718** [comment]
Can someone provide a command sequence to reproduce this? For instance, is this before `./case.setup` (when I would expect it to work) or after (when I would expect it to fail)?
