### ISSUE TITLE
Remove python stack trace when a model run fails

### ISSUE THREAD

**Issue by jayeshkrishna** [ESMCI/cime#1291]
When an ACME/CESM model run fails, the log files (TestStatus.log) contain
a python stack trace that is not very useful to the user (The failure is in
the model run, not in the CIME python framework). 
It would be useful to remove the python stack trace and include a comment
to the location of the log file that the user should look at to diagnose the
failure.

**Comment by jayeshkrishna** [comment]
An example (excerpt from TestStatus.log) of the python stack trace when a model run fails (on blues),
```
2017-03-27 10:04:46: Exception during run:
ERROR: Command: 'mpiexec  -n 1024  /lcrc/project/ACME/acmetest/acme_scratch/SMS.ne30_oEC.A_WCYCL2000.blues_gnu.jenkins_next_20170325_233101/bld/acme.exe  >> acme.log.$LID 2>&1 ' failed with error '' from dir '/lcrc/project/ACME/acmetest/acme_scratch/SMS.ne30_oEC.A_WCYCL2000.blues_gnu.jenkins_next_20170325_233101/run'
Traceback (most recent call last):
  File "/blues/gpfs/home/acmetest/jenkins/workspace/ACME_Blues_next/ACME_Climate/cime/scripts/Tools/../../utils/python/CIME/SystemTests/system_tests_common.py", line 139, in run
    self.run_phase()
  File "/blues/gpfs/home/acmetest/jenkins/workspace/ACME_Blues_next/ACME_Climate/cime/scripts/Tools/../../utils/python/CIME/SystemTests/system_tests_common.py", line 172, in run_phase
    self.run_indv()
  File "/blues/gpfs/home/acmetest/jenkins/workspace/ACME_Blues_next/ACME_Climate/cime/scripts/Tools/../../utils/python/CIME/SystemTests/system_tests_common.py", line 204, in run_indv
    case_run(self._case)
  File "/blues/gpfs/home/acmetest/jenkins/workspace/ACME_Blues_next/ACME_Climate/cime/scripts/Tools/../../utils/python/CIME/case_run.py", line 219, in case_run
    run_model(case)
  File "/blues/gpfs/home/acmetest/jenkins/workspace/ACME_Blues_next/ACME_Climate/cime/scripts/Tools/../../utils/python/CIME/case_run.py", line 98, in run_model
    run_cmd_no_fail(cmd, from_dir=rundir)
  File "/blues/gpfs/home/acmetest/jenkins/workspace/ACME_Blues_next/ACME_Climate/cime/scripts/Tools/../../utils/python/CIME/utils.py", line 211, in run_cmd_no_fail
    (cmd, errput, "" if from_dir is None else " from dir '%s'" % from_dir))
  File "/blues/gpfs/home/acmetest/jenkins/workspace/ACME_Blues_next/ACME_Climate/cime/scripts/Tools/../../utils/python/CIME/utils.py", line 27, in expect
    raise exc_type("%s %s" % (error_prefix,error_msg))
SystemExit: ERROR: Command: 'mpiexec  -n 1024  /lcrc/project/ACME/acmetest/acme_scratch/SMS.ne30_oEC.A_WCYCL2000.blues_gnu.jenkins_next_20170325_233101/bld/acme.exe  >> acme.log.$LID 2>&1 ' failed with error '' from dir '/lcrc/project/ACME/acmetest/acme_scratch/SMS.ne30_oEC.A_WCYCL2000.blues_gnu.jenkins_next_20170325_233101/run'

```

**Comment by mvertens** [comment]
I completely agree with this. I think this recommendation would be a good
step forwards.

**Comment by rljacob** [comment]
Duplicates #541
