### ISSUE TITLE
da_script issue in case.run

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#1379]
Traceback (most recent call last):
  File "/glade/u/spooldir/1492552132.903352.shell", line 84, in <module>
    _main_func(__doc__)
  File "/glade/u/spooldir/1492552132.903352.shell", line 79, in _main_func
    success = case_run(case)
  File "/glade/p/work/marcusl/CESM_model_versions/cesm2_0_beta05_cam5_4_111_finalclm50paramsfile_n12_clm4_5_14_r225/cime/scripts/Tools/../../utils/python/CIME/case_run.py", line 221, in case_run
    do_data_assimilation(data_assimilation_script, case.get_value("CASEROOT"), cycle, lid)
  File "/glade/p/work/marcusl/CESM_model_versions/cesm2_0_beta05_cam5_4_111_finalclm50paramsfile_n12_clm4_5_14_r225/cime/scripts/Tools/../../utils/python/CIME/case_run.py", line 182, in do_data_assimilation
    cmd = da_script + " 1> da.log.%s %d %d 2>&1" %(lid, caseroot, cycle)
TypeError: %d format: a number is required, not str

Should be %s not %d

**Comment by jedwards4b** [comment]
This is already fixed on the trunk.
