### ISSUE TITLE
cime_developer tests failed on anlworkstation and melvin

### ISSUE THREAD

**Issue by dqwu** [ESMCI/cime#1420]
On anlworkstation, cime_developer tests failed during phase SETUP.
```
Starting SETUP for test SMS.T42_T42.S.anlworkstation_gnu with 1 procs
Finished SETUP for test SMS.T42_T42.S.anlworkstation_gnu in 7.438943 seconds (FAIL). [COMPLETED 1 of 1]
    Case dir: /sandbox/jenkins-ci/workspace/CIME_PIO/test_cime_latest_pio2/SMS.T42_T42.S.anlworkstation_gnu.20170426_021128_x46s26
    Errors were:
        /sandbox/jenkins-ci/workspace/CIME_PIO/test_cime_latest_pio2/SMS.T42_T42.S.anlworkstation_gnu.20170426_021128_x46s26/env_mach_specific.xml already exists, delete to replace
        Traceback (most recent call last):
          File "./case.setup", line 71, in <module>
            _main_func(__doc__)
          File "./case.setup", line 68, in _main_func
            case_setup(case, clean=clean, test_mode=test_mode, reset=reset, adjust_pio=adjust_pio)
          File "/sandbox/jenkins-ci/workspace/CIME_PIO/CIME_PIO2_Test/scripts/Tools/../../scripts/lib/CIME/case_setup.py", line 260, in case_setup
            run_and_log_case_status(functor, phase, caseroot=caseroot)
          File "/sandbox/jenkins-ci/workspace/CIME_PIO/CIME_PIO2_Test/scripts/Tools/../../scripts/lib/CIME/utils.py", line 1222, in run_and_log_case_status
            rv = func()
          File "/sandbox/jenkins-ci/workspace/CIME_PIO/CIME_PIO2_Test/scripts/Tools/../../scripts/lib/CIME/case_setup.py", line 254, in <lambda>
            functor = lambda: _case_setup_impl(case, caseroot, clean, test_mode, reset, adjust_pio)
          File "/sandbox/jenkins-ci/workspace/CIME_PIO/CIME_PIO2_Test/scripts/Tools/../../scripts/lib/CIME/case_setup.py", line 163, in _case_setup_impl
            adjust_pio_layout(case, tasks_per_node)
        UnboundLocalError: local variable 'tasks_per_node' referenced before assignment
```
On melvin, there are similar build errors:
http://my.cdash.org/testDetails.php?test=31220347&build=1183410

**Comment by jgfouca** [comment]
I fixed this yesterday.
