### ISSUE TITLE
Additional functionality desired for query_config

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1470]
#1388 is improving query_config, partly to address #1190 . However, many aspects of https://github.com/ESMCI/cime/issues/1190#issuecomment-282928761 are not addressed in that PR.

I see the most important outstanding requests as:

1. For each compset, a listing of which grids are scientifically and test-supported for that compset

1. Allow subsetting compsets by the first letter of the compset, rather than cam/clm/etc., along with some help text saying "B means XXX, F means YYY", etc. This is important because it's not necessarily intuitive that you get I compsets by specifying `--compsets clm`.

**Comment by billsacks** [comment]
So that everything is in one place, here is the comment from #1190 that is referenced above:

----

A number of us at NCAR had a discussion on this tool a few weeks ago, but we neglected to open an issue documenting this. Specifically, this was a meeting with @mvertens @jedwards4b , Keith Oleson, Dave Bailey, Cecile Hannay and myself. The point was to gather requirements and suggestions from some of the CESM science liaisons. Here are my notes from that meeting (with apologies that they're kind of rough):

• What do you (and other users) want to be able to query?

Jim: Can we start with a list of available compsets, showing which are scientifically supported, and showing which grids are scientifically or test supported for each compset?

e.g.,:

```
B1850
    f09_g16
    f19_g16
```

Dave also wants to be able to subset on compset (with --compset)

If you just want to list F compsets, how should you do that?
* Specify allactive, cam, etc. as primary component?
* Cecile prefers that you specify first letter (B, F, I)
    * Accompanied with some help saying what are the available first letters to query on - e.g.:
        * F means XXX
        * I means YYY
    * If you don't specify a letter, it means give me all compsets
* What about something like B1850*
    * Mariana points out that then we're relying on aliases, which she wants to get away from
    * But does something like a wildcard match require you know stuff to begin with that this tool is trying to make it so you don't have to know?

Note that there isn't necessarily a way to query the system on all the available grids for a given compset (you can query the tested grids for a given compset).

• Do you want to see support level (scientifically supported, etc.)?
* If so, do you want to be able to query on combinations of compsets & grids?

• How do you want the information presented?

Dave: Having output to help you craft the create_newcase command would be useful... but maybe not do this for now

• What is the best user interface to this tool?
* Separate tool vs a -list option to create_newcase
* What would the command line options look like?

Dave likes the idea of having a tool to help you before you try to craft a create_newcase command

People like having a separate tool

• Do we want this sort of information on the web?

Mariana has reservations with having this on the web

Jim: Can we automate the generation of the web information?

Dave: Benefit of having it on the web, but don't need to update it too often
* e.g., For someone who hasn't even downloaded the code yet

Cecile echoes Dave's comments – useful to have some information on the web, but more detailed information available in a more complex way.

Cecile uses this:

http://www.cesm.ucar.edu/models/cesm1.2/cesm/doc/modelnl/compsets.html

(though she rarely uses the pop-up info)

So we could list the supported compsets, with long name, alias, and supported grids

**Comment by bertinia** [comment]
The new query_config --grids --long no longer outputs the grid long name and it should.

For example, the output now looks like the following:

     alias: g16_g16 (only for compsets that are DATM.+DROF )
       non-default grids are: atm:gx1v6  lnd:gx1v6  ocnice:gx1v6  
    
       gx1v6 is displaced Greenland pole v6 1-deg grid: with domain file(s): 
       $DIN_LOC_ROOT/share/domains/domain.ocn.gx1v6.090206.nc (only for grid match: atm|lnd)
       $DIN_LOC_ROOT/share/domains/domain.ocn.gx1v6.090206.nc (only for grid match: ocnice) 

where as with manage_case, it looked as follows:

------------------------------------------------
model grid: a%gx1v6_l%gx1v6_oi%gx1v6_r%rx1_m%gx1v6_g%null_w%null
------------------------------------------------
   short name: gx1v6_gx1v6
   alias: g16_g16
   compset match: DATM.+DROF

**Comment by bertinia** [comment]
query_config no longer works for either cime5.4.0-alpha.23 or on master. 
Here is the error for cime5.4.0-alpha.23:

```
[aliceb@cheyenne1:scripts]>./query_config --components clm
Traceback (most recent call last):
  File "./query_config", line 343, in <module>
    _main_func(__doc__)
  File "./query_config", line 336, in _main_func
    query_component(args.components)
  File "./query_config", line 146, in query_component
    if not all_components and not config_exists:
UnboundLocalError: local variable 'config_exists' referenced before assignment
```

and here is the error from master:

```
[aliceb@cheyenne6:scripts]>./query_config --component clm
ERROR: locked
```

**Comment by jedwards4b** [comment]
As far as I can tell these issues have been addressed.  Please reopen if this is not the case.

**Comment by billsacks** [comment]
It may be that the latter comments from @bertinia were addressed, but I don't believe that the original comments in this issue were addressed.

Note that addressing this could partly address @Katetc 's recent issue, #2836 .

**Comment by billsacks** [comment]
@mvertens @jedwards4b @briandobbins and I discussed this issue yesterday. I think the original requests (see https://github.com/ESMCI/cime/issues/1470#issue-226061157) are still unresolved. It feels to us like the right thing to do here is to more closely integrate @alperaltuntas 's GUI work with CIME, and provide similar functionality via the command-line (via query_config or some other tool) as Alper is providing via the GUI.

@alperaltuntas - because this feels so closely related with the GUI work, I am tentatively assigning this to you.
