### ISSUE TITLE
invalid CIME_MODEL environment variable causes untraceable crash

### ISSUE THREAD

**Issue by sarich** [ESMCI/cime#1563]
If I use 'ACME' instead of 'acme', then create_newcase fails without explaining why

$ export CIME_MODEL=ACME
$./create_newcase  --case ACMETEST1 --res ne30_g16 --compset X --mach anlworkstation
```
Traceback (most recent call last):
  File "./create_newcase", line 206, in <module>
    _main_func(__doc__)
  File "./create_newcase", line 177, in _main_func
    with Case(caseroot, read_only=False) as case:
  File "/sandbox/sarich/ACME/cime/scripts/Tools/../../scripts/lib/CIME/case.py", line 79, in __init__
    self.read_xml()
  File "/sandbox/sarich/ACME/cime/scripts/Tools/../../scripts/lib/CIME/case.py", line 184, in read_xml
    self._env_entryid_files.append(EnvCase(self._caseroot, components=None))
  File "/sandbox/sarich/ACME/cime/scripts/Tools/../../scripts/lib/CIME/XML/env_case.py", line 17, in __init__
    EnvBase.__init__(self, case_root, infile, schema=schema)
  File "/sandbox/sarich/ACME/cime/scripts/Tools/../../scripts/lib/CIME/XML/env_base.py", line 25, in __init__
    headernode = headerobj.get_header_node(os.path.basename(fullpath))
  File "/sandbox/sarich/ACME/cime/scripts/Tools/../../scripts/lib/CIME/XML/headers.py", line 26, in get_header_node
    fnode = self.get_node("file", attributes={"name" : fname})
  File "/sandbox/sarich/ACME/cime/scripts/Tools/../../scripts/lib/CIME/XML/generic_xml.py", line 93, in get_node
    nodes = self.get_nodes(nodename, attributes=attributes, root=root, xpath=xpath)
  File "/sandbox/sarich/ACME/cime/scripts/Tools/../../scripts/lib/CIME/XML/generic_xml.py", line 116, in get_nodes
    root = self.root
AttributeError: 'Headers' object has no attribute 'root'
```

**Comment by sarich** [comment]
Sorry, I think I was on an old branch. on current master I get the error message:
ERROR: Could not find or open file /sandbox/sarich/cime4/config/ACME/config_files.xml
