### ISSUE TITLE
advanced-py-prof unable to load standard_script_setup

### ISSUE THREAD

**Issue by mfdeakin-sandia** [ESMCI/cime#1574]
Running on Edison, I get the following output:

```~/ACME/acme_wcycl2000_cime5/cime/scripts/Tools/advanced-py-prof ./case.submit --no-batch
Traceback (most recent call last):
  File "/usr/common/software/python/2.7.9/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/common/software/python/2.7.9/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/global/common/edison/software/python/2.7.9/lib/python2.7/cProfile.py", line 199, in <module>
    main()
  File "/global/common/edison/software/python/2.7.9/lib/python2.7/cProfile.py", line 192, in main
    runctx(code, globs, None, options.outfile, options.sort)
  File "/global/common/edison/software/python/2.7.9/lib/python2.7/cProfile.py", line 49, in runctx
    prof = prof.runctx(statement, globals, locals)
  File "/global/common/edison/software/python/2.7.9/lib/python2.7/cProfile.py", line 140, in runctx
    exec cmd in globals, locals
  File "./case.submit", line 7, in <module>
    from standard_script_setup import *
ImportError: No module named standard_script_setup
```

**Comment by jedwards4b** [comment]
Try PYTHONPATH=$CIMEROOT/scripts/lib prior to running.

**Comment by jedwards4b** [comment]
I mean PYTHONPATH=$CIMEROOT/scripts/lib:$CIMEROOT/scripts/Tools:$PYTHONPATH

**Comment by mfdeakin-sandia** [comment]
Your first one worked :+1: 
Can we update this to work by default, like everything else?

**Comment by mfdeakin-sandia** [comment]
I retract my statement; neither of those lines worked, and I need to pay more attention to what I'm actually running

**Comment by jgfouca** [comment]
What about setting it to $CIMEROOT/scripts?

**Comment by jgfouca** [comment]
Yes, it would be nice to work by default. Problem is the tool would have to know what you're testing.

**Comment by mfdeakin-sandia** [comment]
No; todays an off day for me; it's working, sorry about that
