### ISSUE TITLE
cray machines do not have python collections module

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#169]
Noted on edison:
Traceback (most recent call last):
  File "./scripts_regression_tests", line 8, in <module>
    import CIME.utils, update_acme_tests, wait_for_tests
  File "/global/u1/j/jedwards/cesm1_5_alpha/cime.esmci/utils/python/wait_for_tests.py", line 8, in <module>
    from collections import OrderedDict
ImportError: cannot import name OrderedDict

**Comment by jgfouca** [comment]
what python module was loaded?

**Comment by jedwards4b** [comment]
That was the problem, sorry I thought I had checked.
