### ISSUE TITLE
test_d_retry problem on yellowstone

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#2043]
There seems to be a problem with this test on yellowstone, the TESTBUILDFAIL_P1.f19_g16_rx1.A.yellowstone_intel
PASSES on the second attempt, I can reproduce this behavior consistantly using scripts_regression_tests.py but If I just run TESTBUILDFAIL_P1.f19_g16_rx1.A.yellowstone_intel it
fails everytime (as expected).   Any ideas?

```
======================================================================
FAIL: test_d_retry (__main__.O_TestTestScheduler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./scripts_regression_tests.py", line 1070, in test_d_retry
    self._create_test(args)
  File "./scripts_regression_tests.py", line 813, in _create_test
    expected_stat=expected_stat)
  File "./scripts_regression_tests.py", line 60, in run_cmd_assert_result
    test_obj.assertEqual(stat, expected_stat, msg=msg)
AssertionError: 
COMMAND:  /glade/p/work/jedwards/sandboxes/cesm2_0_alpha/cime/scripts/create_test TESTBUILDFAIL_P1.f19_g16_rx1.A TESTRUNFAIL_P1.f19_g16_rx1.A TESTRUNPASS_P1.f19_g16_rx1.A --retry=1 -t 20171109_140326 --baseline-root /glade/scratch/jedwards/scripts_regression_test.20171109_140320/baselines --test-root=/glade/scratch/jedwards/scripts_regression_test.20171109_140320 --output-root=/glade/scratch/jedwards/scripts_regression_test.20171109_140320
FROM_DIR: /glade/p/work/jedwards/sandboxes/cesm2_0_alpha/cime/scripts/tests
SHOULD HAVE WORKED, INSTEAD GOT STAT 100
OUTPUT: Testnames: ['TESTBUILDFAIL_P1.f19_g16_rx1.A.yellowstone_intel', 'TESTRUNFAIL_P1.f19_g16_rx1.A.yellowstone_intel', 'TESTRUNPASS_P1.f19_g16_rx1.A.yellowstone_intel']
Using project from env PROJECT: CESM0008
Creating test directory /glade/scratch/jedwards/scripts_regression_test.20171109_140320/TESTBUILDFAIL_P1.f19_g16_rx1.A.yellowstone_intel.20171109_140326
Creating test directory /glade/scratch/jedwards/scripts_regression_test.20171109_140320/TESTRUNFAIL_P1.f19_g16_rx1.A.yellowstone_intel.20171109_140326
Creating test directory /glade/scratch/jedwards/scripts_regression_test.20171109_140320/TESTRUNPASS_P1.f19_g16_rx1.A.yellowstone_intel.20171109_140326
RUNNING TESTS:
  TESTBUILDFAIL_P1.f19_g16_rx1.A.yellowstone_intel
  TESTRUNFAIL_P1.f19_g16_rx1.A.yellowstone_intel
  TESTRUNPASS_P1.f19_g16_rx1.A.yellowstone_intel
Starting CREATE_NEWCASE for test TESTBUILDFAIL_P1.f19_g16_rx1.A.yellowstone_intel with 1 procs
Starting CREATE_NEWCASE for test TESTRUNFAIL_P1.f19_g16_rx1.A.yellowstone_intel with 1 procs
Starting CREATE_NEWCASE for test TESTRUNPASS_P1.f19_g16_rx1.A.yellowstone_intel with 1 procs
Finished CREATE_NEWCASE for test TESTBUILDFAIL_P1.f19_g16_rx1.A.yellowstone_intel in 2.535957 seconds (PASS)
Finished CREATE_NEWCASE for test TESTRUNPASS_P1.f19_g16_rx1.A.yellowstone_intel in 2.551518 seconds (PASS)
Finished CREATE_NEWCASE for test TESTRUNFAIL_P1.f19_g16_rx1.A.yellowstone_intel in 2.552595 seconds (PASS)
Starting XML for test TESTBUILDFAIL_P1.f19_g16_rx1.A.yellowstone_intel with 1 procs
Starting XML for test TESTRUNFAIL_P1.f19_g16_rx1.A.yellowstone_intel with 1 procs
Starting XML for test TESTRUNPASS_P1.f19_g16_rx1.A.yellowstone_intel with 1 procs
Finished XML for test TESTBUILDFAIL_P1.f19_g16_rx1.A.yellowstone_intel in 1.374002 seconds (PASS)
Finished XML for test TESTRUNPASS_P1.f19_g16_rx1.A.yellowstone_intel in 1.421210 seconds (PASS)
Finished XML for test TESTRUNFAIL_P1.f19_g16_rx1.A.yellowstone_intel in 1.425648 seconds (PASS)
Starting SETUP for test TESTBUILDFAIL_P1.f19_g16_rx1.A.yellowstone_intel with 1 procs
Starting SETUP for test TESTRUNFAIL_P1.f19_g16_rx1.A.yellowstone_intel with 1 procs
Starting SETUP for test TESTRUNPASS_P1.f19_g16_rx1.A.yellowstone_intel with 1 procs
Finished SETUP for test TESTBUILDFAIL_P1.f19_g16_rx1.A.yellowstone_intel in 3.956019 seconds (PASS)
Starting SHAREDLIB_BUILD for test TESTBUILDFAIL_P1.f19_g16_rx1.A.yellowstone_intel with 1 procs
Finished SETUP for test TESTRUNPASS_P1.f19_g16_rx1.A.yellowstone_intel in 4.023581 seconds (PASS)
Finished SETUP for test TESTRUNFAIL_P1.f19_g16_rx1.A.yellowstone_intel in 4.076013 seconds (PASS)
Finished SHAREDLIB_BUILD for test TESTBUILDFAIL_P1.f19_g16_rx1.A.yellowstone_intel in 1.534378 seconds (PASS)
Starting MODEL_BUILD for test TESTBUILDFAIL_P1.f19_g16_rx1.A.yellowstone_intel with 4 procs
Starting SHAREDLIB_BUILD for test TESTRUNFAIL_P1.f19_g16_rx1.A.yellowstone_intel with 1 procs
Finished MODEL_BUILD for test TESTBUILDFAIL_P1.f19_g16_rx1.A.yellowstone_intel in 1.439846 seconds (FAIL). [COMPLETED 1 of 3]
    Case dir: /glade/scratch/jedwards/scripts_regression_test.20171109_140320/TESTBUILDFAIL_P1.f19_g16_rx1.A.yellowstone_intel.20171109_140326
    Errors were:
        Building test for TESTBUILDFAIL in directory /glade2/scratch2/jedwards/scripts_regression_test.20171109_140320/TESTBUILDFAIL_P1.f19_g16_rx1.A.yellowstone_intel.20171109_140326
        ERROR: BUILD FAIL: Intentional fail for testing infrastructure

Finished SHAREDLIB_BUILD for test TESTRUNFAIL_P1.f19_g16_rx1.A.yellowstone_intel in 1.488618 seconds (PASS)
Starting MODEL_BUILD for test TESTRUNFAIL_P1.f19_g16_rx1.A.yellowstone_intel with 4 procs
Starting SHAREDLIB_BUILD for test TESTRUNPASS_P1.f19_g16_rx1.A.yellowstone_intel with 1 procs
Finished MODEL_BUILD for test TESTRUNFAIL_P1.f19_g16_rx1.A.yellowstone_intel in 1.419215 seconds (PASS)
Finished SHAREDLIB_BUILD for test TESTRUNPASS_P1.f19_g16_rx1.A.yellowstone_intel in 1.518366 seconds (PASS)
Starting MODEL_BUILD for test TESTRUNPASS_P1.f19_g16_rx1.A.yellowstone_intel with 4 procs
Starting RUN for test TESTRUNFAIL_P1.f19_g16_rx1.A.yellowstone_intel with 1 proc on interactive node and 1 procs on compute nodes
Finished MODEL_BUILD for test TESTRUNPASS_P1.f19_g16_rx1.A.yellowstone_intel in 1.567670 seconds (PASS)
Starting RUN for test TESTRUNPASS_P1.f19_g16_rx1.A.yellowstone_intel with 1 proc on interactive node and 1 procs on compute nodes
Finished RUN for test TESTRUNFAIL_P1.f19_g16_rx1.A.yellowstone_intel in 7.315589 seconds (PEND). [COMPLETED 2 of 3]
Finished RUN for test TESTRUNPASS_P1.f19_g16_rx1.A.yellowstone_intel in 6.645838 seconds (PEND). [COMPLETED 3 of 3]
Waiting for tests to finish
Test 'TESTBUILDFAIL_P1.f19_g16_rx1.A.yellowstone_intel' finished with status 'FAIL'
    Path: /glade/scratch/jedwards/scripts_regression_test.20171109_140320/TESTBUILDFAIL_P1.f19_g16_rx1.A.yellowstone_intel.20171109_140326/TestStatus
Test 'TESTRUNFAIL_P1.f19_g16_rx1.A.yellowstone_intel' finished with status 'FAIL'
    Path: /glade/scratch/jedwards/scripts_regression_test.20171109_140320/TESTRUNFAIL_P1.f19_g16_rx1.A.yellowstone_intel.20171109_140326/TestStatus
Test 'TESTRUNPASS_P1.f19_g16_rx1.A.yellowstone_intel' finished with status 'PASS'
    Path: /glade/scratch/jedwards/scripts_regression_test.20171109_140320/TESTRUNPASS_P1.f19_g16_rx1.A.yellowstone_intel.20171109_140326/TestStatus
Using project from env PROJECT: CESM0008
Using existing test directory /glade/scratch/jedwards/scripts_regression_test.20171109_140320/TESTBUILDFAIL_P1.f19_g16_rx1.A.yellowstone_intel.20171109_140326
Using existing test directory /glade/scratch/jedwards/scripts_regression_test.20171109_140320/TESTRUNFAIL_P1.f19_g16_rx1.A.yellowstone_intel.20171109_140326
Test TESTRUNPASS_P1.f19_g16_rx1.A.yellowstone_intel passed and will not be re-run
Using existing test directory /glade/scratch/jedwards/scripts_regression_test.20171109_140320/TESTRUNPASS_P1.f19_g16_rx1.A.yellowstone_intel.20171109_140326
RUNNING TESTS:
  TESTBUILDFAIL_P1.f19_g16_rx1.A.yellowstone_intel
  TESTRUNFAIL_P1.f19_g16_rx1.A.yellowstone_intel
  TESTRUNPASS_P1.f19_g16_rx1.A.yellowstone_intel
Starting MODEL_BUILD for test TESTBUILDFAIL_P1.f19_g16_rx1.A.yellowstone_intel with 4 procs
Starting RUN for test TESTRUNFAIL_P1.f19_g16_rx1.A.yellowstone_intel with 1 procs
Finished MODEL_BUILD for test TESTBUILDFAIL_P1.f19_g16_rx1.A.yellowstone_intel in 8.656065 seconds (PASS)
Finished RUN for test TESTRUNFAIL_P1.f19_g16_rx1.A.yellowstone_intel in 8.660039 seconds (PEND). [COMPLETED 1 of 3]
Starting RUN for test TESTBUILDFAIL_P1.f19_g16_rx1.A.yellowstone_intel with 1 proc on interactive node and 1 procs on compute nodes
Finished RUN for test TESTBUILDFAIL_P1.f19_g16_rx1.A.yellowstone_intel in 6.375755 seconds (PEND). [COMPLETED 2 of 3]
Waiting for tests to finish
Test 'TESTBUILDFAIL_P1.f19_g16_rx1.A.yellowstone_intel' finished with status 'PASS'
    Path: /glade/scratch/jedwards/scripts_regression_test.20171109_140320/TESTBUILDFAIL_P1.f19_g16_rx1.A.yellowstone_intel.20171109_140326/TestStatus
Test 'TESTRUNFAIL_P1.f19_g16_rx1.A.yellowstone_intel' finished with status 'FAIL'
    Path: /glade/scratch/jedwards/scripts_regression_test.20171109_140320/TESTRUNFAIL_P1.f19_g16_rx1.A.yellowstone_intel.20171109_140326/TestStatus
Test 'TESTRUNPASS_P1.f19_g16_rx1.A.yellowstone_intel' finished with status 'PASS'
    Path: /glade/scratch/jedwards/scripts_regression_test.20171109_140320/TESTRUNPASS_P1.f19_g16_rx1.A.yellowstone_intel.20171109_140326/TestStatus
ERRPUT: 
```

**Comment by jedwards4b** [comment]
Actually running : ./create_test --retry 2 TESTBUILDFAIL.f19_g16.X
the test passes on the second run.

**Comment by jedwards4b** [comment]
Oh - now I see this is intentional in create_test, but then why does the scripts_regression_test.py 
indicate FAIL?

**Comment by jedwards4b** [comment]
The actual problem is 
Test 'TESTRUNFAIL_P1.f19_g16_rx1.A.yellowstone_intel' finished with status 'FAIL'
on the second pass, but looking in the TestStatus file it indicates PASS - race condition?

**Comment by jedwards4b** [comment]
I think that the issue is that the TestStatus is not reset to PEND prior to the second run and so wait_for_tests doesn't wait.

**Comment by jgfouca** [comment]
@jedwards4b yes that's it. I've hit that before in similar tests.

**Comment by jgfouca** [comment]
@jedwards4b , actually I don't understand where the problem is. retry=1 should turn on use_existing, which should set the failed states back to PEND.

**Comment by jgfouca** [comment]
For what it's worth, I'm also seeing this problem on skybridge.

**Comment by jgfouca** [comment]
Nevermind, I see the problem.
