### ISSUE TITLE
Initial port of new CIME to mira

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#205]
The latest cime (cime4.4.7-1773-g7eb2814) does not work on Cetus/Mira. The create_test command fails with the following error message,
```
[jayesh@cetuslac1 scripts (master=)]$ ./create_newcase -case cime_sanity_check_cime -compset X -res f19_g16 
Compset longname is 2000_XATM_XLND_XICE_XOCN_XROF_XGLC_XWAV 
Compset specification file is /gpfs/mira-home/jayesh/acme/ESMCI_cime/scripts/Tools/../../driver_cpl/cime_config/config_compsets.xml
Pes     specification file is /gpfs/mira-home/jayesh/acme/ESMCI_cime/scripts/Tools/../../driver_cpl/cime_config/config_pes.xml
Pes setting: grid          is a%1.9x2.5_l%1.9x2.5_oi%gx1v6_r%r05_m%gx1v6_g%null_w%null 
Pes setting: compset       is 2000_XATM_XLND_XICE_XOCN_XROF_XGLC_XWAV 
Pes setting: grid match    is any 
Pes setting: machine match is any 
Pes setting: compset_match is any 
Pes setting: pesize match  is any 
Traceback (most recent call last):
  File "./create_newcase", line 180, in <module>
    _main_func()
  File "./create_newcase", line 165, in _main_func
    walltime=walltime)
  File "/gpfs/mira-home/jayesh/acme/ESMCI_cime/scripts/Tools/../../utils/python/CIME/case.py", line 567, in configure
    env_batch.set_job_defaults(bjobs, pesize=maxval, walltime=walltime)
  File "/gpfs/mira-home/jayesh/acme/ESMCI_cime/scripts/Tools/../../utils/python/CIME/XML/env_batch.py", line 273, in set_job_defaults
    self.set_value( "JOB_WALLCLOCK_TIME", walltime , subgroup=job)
  File "/gpfs/mira-home/jayesh/acme/ESMCI_cime/scripts/Tools/../../utils/python/CIME/XML/env_batch.py", line 36, in set_value
    t = time.strptime(value,"%H:%M:%S")
  File "/soft/interpreters/python-2.7.9/powerpc64-linux-gnu/lib/python2.7/_strptime.py", line 467, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/soft/interpreters/python-2.7.9/powerpc64-linux-gnu/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '59' does not match format '%H:%M:%S'
Exception RuntimeError: 'sys.path must be a list of directory names' in <bound method Case.__del__ of <CIME.case.Case object at 0xfff7f618490>> ignored

```

**Comment by jayeshkrishna** [comment]
Looks like the walltime (in config_batch.xml) in not in the expected format (or the mira walltime format is not supported). "59" vs "0:59:00" .

**Comment by jayeshkrishna** [comment]
After making change to the walltime format for cetus/mira, ./create_newcase ran successfully. However I got the following error with ./case.setup for "-compset X -res f19_g16 ",
```
[jayesh@cetuslac1 cime_sanity_check_cime (master *=)]$ ./case.setup | tee setup.log
ERROR: ATM NINST value 1 greater than ATM NTASKS 0
```

**Comment by jayeshkrishna** [comment]
NTASKS* (for all components) in env_mach_pes.xml is 0 for the case above.

**Comment by jayeshkrishna** [comment]
If I set CIME_MODEL=cesm, I don't get the error above.

**Comment by rljacob** [comment]
And what is NTASKS set to in env_mach_pes.xml?

**Comment by jayeshkrishna** [comment]
@jedwards4b : Does #240 fix this issue?

**Comment by jayeshkrishna** [comment]
NTASKS in env_mach_pes.xml for all components is 0

**Comment by rljacob** [comment]
#240 fixes the walltime problem.

**Comment by jedwards4b** [comment]
If it works in cesm but not acme - look for differences in cime_config/*/machines/config*xml

**Comment by jayeshkrishna** [comment]
After setting CIME_MODEL=cesm I get the following error during case.setup,
```
[jayesh@miralac1 cesm_cime_sanity_check_mira (master *=)]$ ./case.setup | tee setup.log
Checking file env_case
Creating batch script case.run
Writing case.run script
total tasks is: 8
Writing case.st_archive script
total tasks is: 8
Writing case.lt_archive script
total tasks is: 8
Locking file env_mach_pes.xml
Creating user_nl_xxx files for components and cpl
Building ATM usernl files
Building LND usernl files
Building ICE usernl files
Building OCN usernl files
Building ROF usernl files
Building GLC usernl files
Building WAV usernl files
Building ESP usernl files
preview_namelists
ERROR: Could not make directory '/projects/ClimateEnergy/usr/jayesh/cesm_cime_sanity_check_mira/bld/atm/obj', error: [Errno 13] Permission denied: '/projects/ClimateEnergy/usr/jayesh'

```

**Comment by jayeshkrishna** [comment]
Should I try the jedwards4b:single_submit_multiple_compilers branch?

**Comment by jedwards4b** [comment]
That isn't going to fix the directory problem above.   Does the directory /projects/ClimateEnergy/usr/jayesh exist?

**Comment by jayeshkrishna** [comment]
No, but should it? I would assume the format should be something like "/projects/ClimateEnergy/jayesh" (without "/usr")

**Comment by jayeshkrishna** [comment]
After getting the permissions changed for "/projects/ClimateEnergy/usr" (automatically created when Pat ran cime scripts the first time?), the case.setup is running correctly for CIME_MODEL=cesm (X + f19_g16 + mira). So something is missing in the acme side.

**Comment by jayeshkrishna** [comment]
Maybe we should remove "Closes #205" in PR #240?

**Comment by rljacob** [comment]
Done.  But also I'm going to close this because it was really about the initial port.  Open a new issue for bugs with the new CIME on Mira.

**Comment by jayeshkrishna** [comment]
Ok. The following was missing in config_machines.xml on the ACME side (will create a PR for that soon),
```
<PES_PER_NODE>8</PES_PER_NODE> 
```
