### ISSUE TITLE
PFUnit fails on Skybridge

### ISSUE THREAD

**Issue by mfdeakin-sandia** [ESMCI/cime#2088]
Building PFUnit with the CIME instructions (http://esmci.github.io/cime/users_guide/unit_testing.html) and setting the XML variable PFUNIT_PATH fails both N_TestUnitTest tests.
The errors are as follows:
```
======================================================================
ERROR: test_a_unit_test (__main__.N_TestUnitTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./scripts_regression_tests.py", line 218, in test_a_unit_test
    %(unit_test_tool,test_dir,test_spec_dir))
  File "/home/mdeakin/cime/scripts/tests/../lib/CIME/utils.py", line 367, in run_cmd_no_fail
    expect(False, "Command: '{}' failed with error '{}' from dir '{}'".format(cmd, errput, os.getcwd() if from_dir is None else from_dir))
  File "/home/mdeakin/cime/scripts/tests/../lib/CIME/utils.py", line 77, in expect
    raise exc_type(error_prefix + " " + error_msg)
SystemExit: ERROR: Command: '/home/mdeakin/cime/scripts/fortran_unit_testing/run_tests.py --build-dir /gscratch/mdeakin/acme_scratch/skybridge/scripts_regression_test.20171120_131654/TestUnitTests/unit_tester_test --test-spec-dir /home/mdeakin/cime/scripts/fortran_unit_testing/Examples/interpolate_1d/tests' failed with error 'CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PFUNIT_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/mdeakin/cime/scripts/fortran_unit_testing/Examples/interpolate_1d/tests
...
PFUNIT_LIBRARY (ADVANCED)
    linked by target "pFunit_interpolate_exe" in directory /home/mdeakin/cime/scripts/fortran_unit_testing/Examples/interpolate_1d/tests/pFUnit
PFUNIT_MODULE_DIR (ADVANCED)
   used as include directory in directory /home/mdeakin/cime/scripts/fortran_unit_testing/Examples/interpolate_1d/tests
...
```
and
```
ERROR: test_b_cime_f90_unit_tests (__main__.N_TestUnitTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./scripts_regression_tests.py", line 236, in test_b_cime_f90_unit_tests
    %(unit_test_tool,test_dir,test_spec_dir))
  File "/home/mdeakin/cime/scripts/tests/../lib/CIME/utils.py", line 367, in run_cmd_no_fail
    expect(False, "Command: '{}' failed with error '{}' from dir '{}'".format(cmd, errput, os.getcwd() if from_dir is None else from_dir))
  File "/home/mdeakin/cime/scripts/tests/../lib/CIME/utils.py", line 77, in expect
    raise exc_type(error_prefix + " " + error_msg)
SystemExit: ERROR: Command: '/home/mdeakin/cime/scripts/fortran_unit_testing/run_tests.py --build-dir /gscratch/mdeakin/acme_scratch/skybridge/scripts_regression_test.20171120_131654/TestUnitTests/driver_f90_tests --test-spec-dir /home/mdeakin/cime' failed with error 'CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PFUNIT_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/mdeakin/cime
...
PFUNIT_LIBRARY (ADVANCED)
    linked by target "avect_wrapper_exe" in directory /home/mdeakin/cime/src/drivers/mct/unit_test/avect_wrapper_test
...
PFUNIT_MODULE_DIR (ADVANCED)
   used as include directory in directory /home/mdeakin/cime
```

**Comment by mfdeakin-sandia** [comment]
I had a typo in my config_compilers variable
