### ISSUE TITLE
CIME error with python >= version 2.7.14

### ISSUE THREAD

**Issue by vanroekel** [ESMCI/cime#2091]
Using python 2.7.14, I get a value error in case.submit on anvil with E3SM, the traceback follows
```
Traceback (most recent call last):
  File "/var/spool/torque/mom_priv/jobs/1788221.bmgt1.lcrc.anl.gov.SC", line 87, in <module>
    _main_func(__doc__)
  File "/var/spool/torque/mom_priv/jobs/1788221.bmgt1.lcrc.anl.gov.SC", line 82, in _main_func
    success = case_run(case, skip_pnl=skip_pnl)
  File "/blues/gpfs/home/lvanroe/acme_master/cime/scripts/Tools/../../scripts/lib/CIME/case_run.py", line 290, in case_run
    lid = run_model(case, lid, skip_pnl)
  File "/blues/gpfs/home/lvanroe/acme_master/cime/scripts/Tools/../../scripts/lib/CIME/case_run.py", line 147, in run_model
    return run_and_log_case_status(functor, "case.run", caseroot=case.get_value("CASEROOT"))
  File "/blues/gpfs/home/lvanroe/acme_master/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 1359, in run_and_log_case_status
    rv = func()
  File "/blues/gpfs/home/lvanroe/acme_master/cime/scripts/Tools/../../scripts/lib/CIME/case_run.py", line 146, in <lambda>
    functor = lambda: _run_model_impl(case, lid, skip_pnl=skip_pnl)
  File "/blues/gpfs/home/lvanroe/acme_master/cime/scripts/Tools/../../scripts/lib/CIME/case_run.py", line 83, in _run_model_impl
    pre_run_check(case, lid, skip_pnl=skip_pnl)
  File "/blues/gpfs/home/lvanroe/acme_master/cime/scripts/Tools/../../scripts/lib/CIME/case_run.py", line 40, in pre_run_check
    case.load_env()
  File "/blues/gpfs/home/lvanroe/acme_master/cime/scripts/Tools/../../scripts/lib/CIME/case.py", line 1238, in load_env
    env_module.load_env(self)
  File "/blues/gpfs/home/lvanroe/acme_master/cime/scripts/Tools/../../scripts/lib/CIME/XML/env_mach_specific.py", line 82, in load_env
    self.load_modules(modules_to_load)
  File "/blues/gpfs/home/lvanroe/acme_master/cime/scripts/Tools/../../scripts/lib/CIME/XML/env_mach_specific.py", line 108, in load_modules
    self._load_modules_generic(modules_to_load)
  File "/blues/gpfs/home/lvanroe/acme_master/cime/scripts/Tools/../../scripts/lib/CIME/XML/env_mach_specific.py", line 309, in _load_modules_generic
    os.environ[key] = newenv[key]
  File "/lcrc/group/acme/lvanroe/conda/lib/python2.7/os.py", line 473, in __setitem__
    putenv(key, item)
ValueError: illegal environment variable name
```
case.submit appears to be failing when loading the ```LS_COLORS=.........```.  Indeed the python 2.7.14 release docs (https://raw.githubusercontent.com/python/cpython/c707893f9cee870bba8364b3a06eb9cfa3b80e58/Misc/NEWS) show that equal signs are now prohibited in environmental variables with putenv, and this is the problem here.

This should be reproducible on any platform with python 2.7.14.

**Comment by jedwards4b** [comment]
Is this because you are trying to set LS_COLORS in the config_machines.xml file?   Not to argue the point that you have found a problem but why would you do that?

**Comment by vanroekel** [comment]
This is the default configuration for anvil in cime.  I'm not adding anything special and the LS_COLORS variable is not in config_machines.xml.  In fact I have searched in vain to see where that variable is being set.  I agree with you that setting this variable makes no sense.

**Comment by pwolfram** [comment]
@jedwards4b, can you please comment on why this issue has been closed?  I've had a similar issue here too and concur that this is indeed a bug that cause E3SM to break on the current version (as of yesterday).  It would be great if this could be fixed.  

If it isn't a bug but user error, e.g., the issue is related to specific set up on the user end, it would be helpful to know how to avoid this conflict.  

Any advice you can provide is greatly appreciated.  Thanks!

**Comment by jedwards4b** [comment]
Yes, this needs to be reworked.

**Comment by jedwards4b** [comment]
@jgfouca do you have time to look into this?  In particular we should be using the python interface to modules and avoid loading the full environment.

**Comment by jgfouca** [comment]
@jedwards4b , yes, I can look

**Comment by pwolfram** [comment]
Thanks @jedwards4b and @jgfouca!
