### ISSUE TITLE
Potential memory leak in PIO1

### ISSUE THREAD

**Issue by mfdeakin-sandia** [ESMCI/cime#2154]
Running ~/ACME/cime/scripts/create_newcase --case f_ompi_sanitize_test --compset F1850C5AV1C-04P2 --res ne4_ne4 --pecount S --compiler gnu --mach anvil --mpilib openmpi with CAM with the address sanitizer, address sanitizer reports a superset ([awcycl_memory_leaks.txt](https://github.com/ESMCI/cime/files/1569908/awcycl_memory_leaks.txt)) of the leaks below:
```
    #0 0x2aaf39c4805a in __interceptor_malloc /blues/gpio_initdecomp_dof_i8 /blues/gpfs/home/mdeakin/ACME/cime/src/externals/pio1/pio/piolib_mod.F90:1189
    #0 0x2ad12dbb405a in __interceptor_malloc /blues/gpfs/home/software/spack/var/spack/stage/gcc-5.3.0-fygfl7rvyuiteto27dlhmil/ACME/cime/src/externals/pio1/pio/piolib_mod.F90:990
    #0 0x2aff131b505a i_mod_MOD_pio_initdecomp_dof_i4 /blues/gpfs/home/mdeakin/ACME/cime/src/externals/pio1/pio/piolib_mod.F90:990
    #0 0x2b000e6eb  #5 0x54af60c in __piolib_mod_MOD_pio_initdecomp_dof_i8 /blues/gpfs/home/mdeakin/ACME/cime/src/externals/pio1/pio/piolib_mod.F90:1189
    #0 0x2b438850705a in __interceptor_malloc /blues/gpfs/home/software/spack/var/spack/stage/gcc-5.3.0-fygfl7rvyuiteto27dlhmilp5cstw2o2/gcc-5.3.0/libsanitizer/asitdecomp_dof_i8 /blues/gpfs/home/mdeakin/ACME/cime/src/externals/pio1/pio/piolib_mod.F90:1189
    #0 0x2b808408405a in __interceptor_malloc /blues/gpfs/home/softwarkin/ACME/cime/src/externals/pio1/pio/piolib_mod.F90:1189
```

**Comment by mfdeakin-sandia** [comment]
Should I care about reported leaks in PIO1? I've been working on this today, it seems complicated to fix.

**Comment by mfdeakin-sandia** [comment]
To clarify, this one looks complicated to fix, the one I originally reported was easy:
```
Direct leak of 4986600 byte(s) in 4 object(s) allocated from:
    #0 0x2ae7fcfd505a in __interceptor_malloc /blues/gpfs/home/software/spack/var/spack/stage/gcc-5.3.0-fygfl7rvyuiteto27dlhmilp5cstw2o2/gcc-5.3.0/libsanitizer/asan/asan_malloc_linux.cc:38
    #1 0x5617204 in __alloc_mod_MOD_alloc_check_1d_long /lcrc/group/acme/mdeakin/acme_scratch/sanitize_test.mt_fixes/bld/gnu/openmpi/debug/nothreads/pio/pio1/pio/alloc_mod.F90:92
    #2 0x56721e4 in compute_counts /lcrc/group/acme/mdeakin/acme_scratch/sanitize_test.mt_fixes/bld/gnu/openmpi/debug/nothreads/pio/pio1/pio/box_rearrange.F90:1383
    #3 0x5677c27 in __box_rearrange_MOD_box_rearrange_create /lcrc/group/acme/mdeakin/acme_scratch/sanitize_test.mt_fixes/bld/gnu/openmpi/debug/nothreads/pio/pio1/pio/box_rearrange.F90:1070
    #4 0x5617718 in __rearrange_MOD_rearrange_create_box_ /lcrc/group/acme/mdeakin/acme_scratch/sanitize_test.mt_fixes/bld/gnu/openmpi/debug/nothreads/pio/pio1/pio/rearrange.F90:165
    #5 0x554e5dc in __piolib_mod_MOD_pio_initdecomp_dof_i8 /blues/gpfs/home/mdeakin/ACME/cime/src/externals/pio1/pio/piolib_mod.F90:1189
    #6 0x1b47455 in __mpas_io_MOD_mpas_io_set_var_indices /lcrc/group/acme/mdeakin/acme_scratch/sanitize_test.mt_fixes/bld/ice/source/framework/mpas_io.f90:1301
    #7 0x2b26788 in __mpas_io_streams_MOD_mpas_streamaddfield_generic /lcrc/group/acme/mdeakin/acme_scratch/sanitize_test.mt_fixes/bld/ice/source/framework/mpas_io_streams.f90:2404
    #8 0x2b315c0 in __mpas_io_streams_MOD_mpas_streamaddfield_2dreal /lcrc/group/acme/mdeakin/acme_scratch/sanitize_test.mt_fixes/bld/ice/source/framework/mpas_io_streams.f90:1430
    #9 0x1bac770 in build_stream /lcrc/group/acme/mdeakin/acme_scratch/sanitize_test.mt_fixes/bld/ice/source/framework/mpas_stream_manager.f90:4243
    #10 0x1bbbe12 in read_stream /lcrc/group/acme/mdeakin/acme_scratch/sanitize_test.mt_fixes/bld/ice/source/framework/mpas_stream_manager.f90:3624
    #11 0x1bc0fd4 in __mpas_stream_manager_MOD_mpas_stream_mgr_read /lcrc/group/acme/mdeakin/acme_scratch/sanitize_test.mt_fixes/bld/ice/source/framework/mpas_stream_manager.f90:3450
    #12 0x4d1e7cd in __ocn_forward_mode_MOD_ocn_forward_mode_init /lcrc/group/acme/mdeakin/acme_scratch/sanitize_test.mt_fixes/bld/ocn/source/core_ocean/mode_forward/mpas_ocn_forward_mode.f90:168
    #13 0x4d1b938 in __ocn_core_MOD_ocn_core_init /lcrc/group/acme/mdeakin/acme_scratch/sanitize_test.mt_fixes/bld/ocn/source/core_ocean/driver/mpas_ocn_core.f90:76
    #14 0x41d415d in __ocn_comp_mct_MOD_ocn_init_mct /lcrc/group/acme/mdeakin/acme_scratch/sanitize_test.mt_fixes/bld/ocn/source/ocean_cesm_driver/ocn_comp_mct.f90:511
    #15 0x42fbf9 in __component_mod_MOD_component_init_cc /blues/gpfs/home/mdeakin/ACME/cime/src/drivers/mct/main/component_mod.F90:258
    #16 0x4197ff in __cime_comp_mod_MOD_cime_init /blues/gpfs/home/mdeakin/ACME/cime/src/drivers/mct/main/cime_comp_mod.F90:1192
    #17 0x429798 in cime_driver /blues/gpfs/home/mdeakin/ACME/cime/src/drivers/mct/main/cime_driver.F90:92
    #18 0x4298db in main /blues/gpfs/home/mdeakin/ACME/cime/src/drivers/mct/main/cime_driver.F90:23
    #19 0x2ae803789d1c in __libc_start_main (/lib64/libc.so.6+0x1ed1c)
```

**Comment by rljacob** [comment]
I don't think you have to worry about fixing them.
