### ISSUE TITLE
Sporadic failure in test teardown for scripts_regression_tests: test_run_restart

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2178]
On NCAR's hobart machine, I got an error in test teardown for `T_TestRunRestart`: `test_run_restart`:

```
======================================================================
ERROR: test_run_restart (__main__.T_TestRunRestart)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./scripts_regression_tests.py", line 795, in tearDown
    shutil.rmtree(file_to_clean)
  File "/usr/lib64/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib64/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/scratch/cluster/sacks/scripts_regression_test.20180102_093035/NODEFAIL_P1.f09_g16.X.hobart_intel.fake_testing_only_20180102_100341'
```

This passed when I reran it (with `nohup ./scripts_regression_tests.py T_TestRunRestart > nohup_t_retry &`).

(This was from 52fed01).

**Comment by jgfouca** [comment]
Potential file system lag?

**Comment by billsacks** [comment]
I haven't seen this issue in a while, so I'm closing it.
