### ISSUE TITLE
scripts_regression_tests: A_RunUnitTests fail from detached head

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2214]
If I have checked out master (currently at f44bca3), `./scripts_regression_tests.py A_RunUnitTests` passes. However, if I have a detached head checked out at f44bca3, I get this failure:

```
======================================================================
FAIL: test_CIME_doctests (__main__.A_RunUnitTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./scripts_regression_tests.py", line 112, in test_CIME_doctests
    run_cmd_assert_result(self, "PYTHONPATH=%s:$PYTHONPATH python -m doctest *.py 2>&1" % LIB_DIR, from_dir=os.path.join(LIB_DIR,"CIME"))
  File "./scripts_regression_tests.py", line 60, in run_cmd_assert_result
    test_obj.assertEqual(stat, expected_stat, msg=msg)
AssertionError:
COMMAND: PYTHONPATH=/glade/p/work/sacks/cime/scripts/lib:$PYTHONPATH python -m doctest *.py 2>&1
FROM_DIR: /glade/p/work/sacks/cime/scripts/lib/CIME
SHOULD HAVE WORKED, INSTEAD GOT STAT 1
OUTPUT: No handlers could be found for logger "utils"
**********************************************************************
File "utils.py", line 537, in utils.get_current_branch
Failed example:
    get_current_branch() is not None
Expected:
    True
Got:
    False
**********************************************************************
1 items had failures:
   1 of   1 in utils.get_current_branch
***Test Failed*** 1 failures.
ERRPUT:


----------------------------------------------------------------------
Ran 4 tests in 1.208s

FAILED (failures=1)
```

**Comment by jgfouca** [comment]
I will fix.
