### ISSUE TITLE
UnicodeEncodeError in scripts/lib/CIME/buildlib.py

### ISSUE THREAD

**Issue by dqwu** [ESMCI/cime#2227]
This is reproducible on anlworkstation

```
./create_test ERR.f45_g37_rx1.A --machine=anlworkstation --test-root=$TEST_ROOT
...
Starting MODEL_BUILD for test ERR.f45_g37_rx1.A.anlworkstation_gnu with 4 procs
Finished MODEL_BUILD for test ERR.f45_g37_rx1.A.anlworkstation_gnu in 5.160113 seconds (FAIL).
...
ERROR: BUILD FAIL: sesp.buildlib failed
```
The content of bld/esp.bldlog.xxxx is:
```
Traceback (most recent call last):
  File "src/components/stub_comps/sesp/cime_config/buildlib", line 35, in <module>
    _main_func(sys.argv)
  File "src/components/stub_comps/sesp/cime_config/buildlib", line 31, in _main_func
    buildlib(caseroot, libroot, bldroot)
  File "src/components/stub_comps/sesp/cime_config/buildlib", line 27, in buildlib
    build_cime_component_lib(case, compname, libroot, bldroot)
  File "scripts/lib/CIME/buildlib.py", line 58, in build_cime_component_lib
    run_gmake(case, compclass, libroot, bldroot)
  File "scripts/lib/CIME/buildlib.py", line 85, in run_gmake
    print(out)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 1753: ordinal not in range(128)
```
Workaround:
If we modify print(out) to print(out.encode('utf-8')) MODEL_BUILD can pass.

Do we have a better fix for this kind of issue?

**Comment by jedwards4b** [comment]
Thanks for finding this, I don't know of a better fix.

**Comment by jgfouca** [comment]
I have a fix coming.

**Comment by jedwards4b** [comment]
I stuck it in 2229, should I remove that?
