### ISSUE TITLE
query_config --component not working for E3SM

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#2297]
output from scripts_regression_tests:
```
======================================================================
ERROR: test_query_components (__main__.X_TestQueryConfig)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./scripts_regression_tests.py", line 1452, in test_query_components
    run_cmd_no_fail("{}/query_config --components".format(SCRIPT_DIR))
  File "/lcrc/group/earthscience/jacob/cimeESMCI2/scripts/tests/../lib/CIME/utils.py", line 424, in run_cmd_no_fail
    expect(False, "Command: '{}' failed with error '{}' from dir '{}'".format(cmd, errput.encode('utf-8'), os.getcwd() if from_dir is None else from_dir))
  File "/lcrc/group/earthscience/jacob/cimeESMCI2/scripts/tests/../lib/CIME/utils.py", line 112, in expect
    raise exc_type(msg)
SystemExit: ERROR: Command: '/lcrc/group/earthscience/jacob/cimeESMCI2/scripts/query_config --components' failed with error 'ERROR: Expected one child' from dir '/lcrc/group/earthscience/jacob/cimeESMCI2/scripts/tests'
```

**Comment by rljacob** [comment]
Just running it at the command line:
```
blogin1[99]: ./query_config --component dwav
ERROR: Expected one child
Exit 1
```
