### ISSUE TITLE
Error for a ERS_Lm1 test

### ISSUE THREAD

**Issue by bishtgautam** [ESMCI/cime#2313]
I created a `ERS_Lm1` test with E3SM and it failed with the following error:

```
2018-02-23 08:15:29: Exception during run:
ERROR: ERROR: stop_n value 1 too short
Traceback (most recent call last):
  File "/global/project/projectdirs/acme/gbisht/Projects/ACME/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_common.py", line 145, in run
    self.run_phase()
  File "/global/project/projectdirs/acme/gbisht/Projects/ACME/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/ers.py", line 47, in run_phase
    self._ers_first_phase()
  File "/global/project/projectdirs/acme/gbisht/Projects/ACME/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/ers.py", line 23, in _ers_first_phase
    expect(stop_n > 2, "ERROR: stop_n value {:d} too short".format(stop_n))
  File "/global/project/projectdirs/acme/gbisht/Projects/ACME/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 112, in expect
    raise exc_type(msg)
SystemExit: ERROR: ERROR: stop_n value 1 too short
```

Is there a bug in the [CIME code](https://github.com/ESMCI/cime/blob/master/scripts/lib/CIME/SystemTests/ers.py#L23) as it is only checking for `STOP_N` while ignoring `STOP_OPTION`?

**Comment by ekluzek** [comment]
It's a limitation, but I wouldn't call it a bug. It calculates when to do the restart in the middle of the simulation time based on the STOP_N value. So you need it to be at least 2, so it can break it up. But, I think it also likes multiple of threes.

Personally I think this is a WONTFIX, because you can workaround it by doing something like _Ld31 to make sure you do at least a full month, but can do a restart somewhere in the middle of that.

**Comment by gold2718** [comment]
I agree with @ekluzek unless you want to enhance the math inside the ERS test code (i.e., turn 1 month into 30 days or turn 1 day into 24 hours etc.)

**Comment by billsacks** [comment]
I third the agreement. You actually need STOP_N to be at least 3. Multiples of 3 doesn't matter: it just needs to be >= 3.

**Comment by rljacob** [comment]
There is at least a documentation problem.  "Don't use a large STOP_OPTION (month, year) unless STOP_N will be greater then or equal to 3".   Where should that be written down?

**Comment by rljacob** [comment]
Also create_test should give a helpful error message if STOP_N isn't big enough.

**Comment by bishtgautam** [comment]
Thanks for suggesting alternate ways of running a month long ERS test via ERS_Ld30.

**Comment by mvertens** [comment]
Can an issue please be raised to have this error statement put in?
