### ISSUE TITLE
py3 error 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#2558]
PR #2511 seems to be causing the following error when run with python3:
```
       Submit job case.st_archive
        Traceback (most recent call last):
          File "./case.submit", line 105, in <module>
            _main_func(__doc__)
          File "./case.submit", line 102, in _main_func
            mail_user=mail_user, mail_type=mail_type, batch_args=batch_args)
          File "/home/jedwards/cesm/scratch/cime-nightly-build/cime/scripts/Tools/../../scripts/lib/CIME/case/case_submit.py", line 156, in submit
            custom_success_msg_functor=verbatim_success_msg)
          File "/home/jedwards/cesm/scratch/cime-nightly-build/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 1609, in run_and_log_case_status
            rv = func()
          File "/home/jedwards/cesm/scratch/cime-nightly-build/cime/scripts/Tools/../../scripts/lib/CIME/case/case_submit.py", line 154, in <lambda>
            batch_args=batch_args)
          File "/home/jedwards/cesm/scratch/cime-nightly-build/cime/scripts/Tools/../../scripts/lib/CIME/case/case_submit.py", line 99, in _submit
            mail_type=mail_type, batch_args=batch_args)
          File "/home/jedwards/cesm/scratch/cime-nightly-build/cime/scripts/Tools/../../scripts/lib/CIME/case/case.py", line 1207, in submit_jobs
            batch_args=batch_args, dry_run=dry_run)
          File "/home/jedwards/cesm/scratch/cime-nightly-build/cime/scripts/Tools/../../scripts/lib/CIME/XML/env_batch.py", line 485, in submit_jobs
            dry_run=dry_run)
          File "/home/jedwards/cesm/scratch/cime-nightly-build/cime/scripts/Tools/../../scripts/lib/CIME/XML/env_batch.py", line 565, in _submit_single_job
            getattr(case, function_name)(**{k: v for k, (v, _) in args.items()})
        TypeError: case_st_archive() got an unexpected keyword argument 'submit_resubmits'
```

**Comment by jedwards4b** [comment]
I think that the problem is not the py3 but rather that this machine does not have a batch system.
