### ISSUE TITLE
Cryptic message if xmlchange is run without any arguments

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2583]
The usage documentation for xmlchange suggests that listofsettings is an optional argument, based on nargs="?" in:

```python
    parser.add_argument("listofsettings", nargs="?", default='',
                        help="Comma seperated list of settings in the form: var1=value,var2=value,...")
```

However, running xmlchange without an argument gives a traceback:

```
$ ./xmlchange
Traceback (most recent call last):
  File "./xmlchange", line 150, in <module>
    _main_func(__doc__)
  File "./xmlchange", line 147, in _main_func
    xmlchange(caseroot, listofsettings, xmlfile, xmlid, xmlval, subgroup, append, noecho, force, dry)
  File "./xmlchange", line 134, in xmlchange
    xmlchange_single_value(case, xmlid, xmlval, subgroup, append, force, dryrun)
  File "./xmlchange", line 89, in xmlchange_single_value
    type_str = case.get_type_info(xmlid)
  File "/Users/sacks/cime/scripts/Tools/../../scripts/lib/CIME/case/case.py", line 341, in get_type_info
    result = env_file.get_type_info(item)
  File "/Users/sacks/cime/scripts/Tools/../../scripts/lib/CIME/XML/entry_id.py", line 149, in get_type_info
    vid, _, _ = self.check_if_comp_var(vid)
  File "/Users/sacks/cime/scripts/Tools/../../scripts/lib/CIME/XML/env_base.py", line 112, in check_if_comp_var
    if vid.endswith('_'+comp):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

My initial inclination was that we should remove the nargs="?" from listofsettings, making it a required argument. But the default of '', together with this line

https://github.com/ESMCI/cime/blob/fcebaadcf66024036f306f2d000ffd040f4fe5c7/scripts/Tools/xmlchange#L82

make me think that, at least at some point, excluding this argument was an allowed operation.

If I understand the logic of this block correctly:

https://github.com/ESMCI/cime/blob/fcebaadcf66024036f306f2d000ffd040f4fe5c7/scripts/Tools/xmlchange#L125-L137

it looks like the main part of the conditional (under `if len(listofsettings):`) is executed whenever there is one or more settings, and the else block is only entered if there are 0 settings (at which point it fails).

**Comment by billsacks** [comment]
Oh, I see now: this is to support the old and new-style usages of xmlchange. I'll fix this to give a more meaningful error message on the  mvertens/documentation_updates branch.
