### ISSUE TITLE
PET tests can't be rebuilt/resubmitted, they must be redone..

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#2595]
I found this with latest CTSM and cime5.6.6, as well as some previous versions of cime as well. It shows up for me for the following tests

PET_P36x2_D.f10_f10_musgs.I1850Clm50BgcCrop.cheyenne_gnu.clm-default		
PET_P36x2_D.f10_f10_musgs.I1850Clm50BgcCrop.cheyenne_intel.clm-default

If they fail, I can rebuild and resubmit, but the resubmit fails as follows. The rebuild works fine.

```
1850Clm50BgcCrop.cheyenne_intel.clm-default.GC.clm50dev010chintela.test.o9353742 
Running test for PET
WARNING: Found difference in test HIST_N: case: $STOP_N original value -999
Doing second run: threads set to 1
Setting resource.RLIMIT_STACK to -1 from (-1, -1)
doing an 5 ndays startup test, no restarts written
File /glade/p/work/erik/ctsm/cime/scripts/cases/PET_P36x2_D.f10_f10_musgs.I1850Clm50BgcCrop.cheyenne_intel.clm-default.GC.clm50dev010chintela/case2/PET_P36x2_D.f10_f10_musgs.I1850Clm50BgcCrop.cheyenne_intel.clm-default.GC.clm50dev010chintela/LockedFiles/env_mach_pes.xml has been modified
  found difference in NTHRDS : case 1 locked 2
Exception during run:
ERROR: Invoke case.setup --reset 
Traceback (most recent call last):
  File "/glade/p/work/erik/ctsm/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_common.py", line 145, in run
    self.run_phase()
  File "/glade/p/work/erik/ctsm/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_compare_two.py", line 239, in run_phase
    self.run_indv(suffix = self._run_two_suffix)
  File "/glade/p/work/erik/ctsm/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_common.py", line 226, in run_indv
    self._case.case_run(skip_pnl=self._skip_pnl)
  File "/glade/p/work/erik/ctsm/cime/scripts/Tools/../../scripts/lib/CIME/case/case_run.py", line 284, in case_run
    lid = _run_model(self, lid, skip_pnl, da_cycle=cycle)
  File "/glade/p/work/erik/ctsm/cime/scripts/Tools/../../scripts/lib/CIME/case/case_run.py", line 163, in _run_model
    return run_and_log_case_status(functor, "case.run", caseroot=case.get_value("CASEROOT"))
  File "/glade/p/work/erik/ctsm/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 1609, in run_and_log_case_status
    rv = func()
  File "/glade/p/work/erik/ctsm/cime/scripts/Tools/../../scripts/lib/CIME/case/case_run.py", line 162, in <lambda>
    functor = lambda: _run_model_impl(case, lid, skip_pnl=skip_pnl, da_cycle=da_cycle)
  File "/glade/p/work/erik/ctsm/cime/scripts/Tools/../../scripts/lib/CIME/case/case_run.py", line 81, in _run_model_impl
    _pre_run_check(case, lid, skip_pnl=skip_pnl, da_cycle=da_cycle)
  File "/glade/p/work/erik/ctsm/cime/scripts/Tools/../../scripts/lib/CIME/case/case_run.py", line 34, in _pre_run_check
    case.check_lockedfiles()
  File "/glade/p/work/erik/ctsm/cime/scripts/Tools/../../scripts/lib/CIME/case/check_lockedfiles.py", line 124, in check_lockedfiles
    self.check_lockedfile(fpart)
  File "/glade/p/work/erik/ctsm/cime/scripts/Tools/../../scripts/lib/CIME/case/check_lockedfiles.py", line 81, in check_lockedfile
    expect(False, "Invoke case.setup --reset ")
  File "/glade/p/work/erik/ctsm/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 130, in expect
    raise exc_type(msg)
SystemExit: ERROR: Invoke case.setup --reset 
```

**Comment by jedwards4b** [comment]
I tested by doing two runs of PET.f10_f10_musgs.I1850Clm50BgcCrop.cheyenne_gnu.clm-default with the latest cime.   Both worked correctly.   I don't think that we can always guarantee that when a test dies in a failed state it will be prepared to run again with a simple case.submit.

**Comment by billsacks** [comment]
@jedwards4b I'm wondering if there needs to be a case_setup call for case2? Here's what I see:

- Prior to 7bc7897fb, pet.py had a case_setup call for both case1 and case2

- In 7bc7897fb, you moved the case_setup call into system_tests_compare_two for all tests; it was still being done for case1 and case2

- In 3920415cd, you moved the case_setup call for case2 out of `_setup_cases` into `run_phase`

- In 283deff8d, you removed the case_setup call for case2 entirely, instead setting `self._skip_pnl = False`.

This disappearance of case_setup for case2 seems suspicious to me.

**Comment by jedwards4b** [comment]
Again - I am not able to reproduce the problem.  I can't fix an issue that doesn't appear to be there. 
I repeated with PET_P36x2_D.f10_f10_musgs.I1850Clm50BgcCrop.cheyenne_gnu.clm-default
and was able to successfully run the test twice.   I suggest that we take the cesm2 milestone off this issue.

**Comment by ekluzek** [comment]
What if you have it abort after running case1?

I removed the cesm2 milestone from it. But, in the long run, we need a way to test that you can still rerun if tests are interrupted in the middle of running. There could be a point (or points) where it dies early if a particular flag is set.

**Comment by billsacks** [comment]
Whoa, it looks like there are bigger issues than just not being able to resubmit: it looks like the pet test is completely not working: it's basically acting as a smoke test (case2 never runs and comparisons between the two cases are never performed). I'm opening a new issue for this.

**Comment by ekluzek** [comment]
There was a commit that addressed this, and I think this is working now. So I'm closing.
