### ISSUE TITLE
KeyError in buildnml if skip_default_entry="true"

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#2669]
If you define a namelist group where every entry has the property, `skip_default_entry="true"`, then when trying to build the namelist, the group does not appear to be parsed, generating a 'KeyError'.
```
Traceback (most recent call last):
  File "./preview_namelists", line 57, in <module>
    _main_func(__doc__)
  File "./preview_namelists", line 54, in _main_func
    case.create_namelists(component=args.component)
  File "/home/goldy/Projects/cesm_dart_pr/cime/scripts/Tools/../../scripts/lib/CIME/case/preview_namelists.py", line 88, in create_namelists
    run_sub_or_cmd(cmd, (caseroot), "buildnml", (self, caseroot, compname), case=self)
  File "/home/goldy/Projects/cesm_dart_pr/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 345, in run_sub_or_cmd
    getattr(mod, subname)(*subargs)
  File "/home/goldy/Projects/cesm_dart_pr/components/dart//cime_config/buildnml", line 176, in buildnml
    _create_namelists(case, confdir, namelist_infile, nmlgen)
  File "/home/goldy/Projects/cesm_dart_pr/components/dart//cime_config/buildnml", line 106, in _create_namelists
    'model_nml', 'filter_nml'])
  File "/home/goldy/Projects/cesm_dart_pr/cime/scripts/Tools/../../scripts/lib/CIME/nmlgen.py", line 645, in write_output_file
    self._namelist.write(namelist_file, groups=groups, sorted_groups=sorted_groups)
  File "/home/goldy/Projects/cesm_dart_pr/cime/scripts/Tools/../../scripts/lib/CIME/namelist.py", line 1156, in write
    self._write(file_obj, groups, format_, sorted_groups=sorted_groups)
  File "/home/goldy/Projects/cesm_dart_pr/cime/scripts/Tools/../../scripts/lib/CIME/namelist.py", line 1176, in _write
    group = self._groups[group_name]
KeyError: 'model_nml'
```

**Comment by gold2718** [comment]
This may be a 'bug' that should not be fixed. The way I think it works, the namelist would not show up in the file unless there were entries in the `user_nl_<comp>` file which would give heartburn to many namelist reading routines.
Thoughts?
@jedwards4b, do you recall why you only read the first file passed into `NamelistGenerator.init_defaults`?

**Comment by jedwards4b** [comment]
I do not, I could look at it in the near future if needed but this is really @mvertens area of expertise.
