### ISSUE TITLE
Empty .cesm_proj file results in a crash

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2677]
I'm opening this issue on behalf of @JeremyFyke . He has an empty `.cesm_proj` file in his home directory on cheyenne. When he ran:

```
create_newcase \
                           --case $D/$CaseName \
                           --compset B1850G \
                           --res f09_g17_gl4 \
                           --mach cheyenne \
                           --project $ProjCode \
                           --run-unsupported
```

He got this traceback:

```
No charge_account info available, using value from PROJECT
Traceback (most recent call last):
  File "/glade/u/home/jfyke/cesm-scripts/Coupled_BG_JG_Spinup_CESM2_Production/Model_Version/cesm2.0.0/cime/scripts/create_newcase", line 218, in <module>
    _main_func(__doc__)
  File "/glade/u/home/jfyke/cesm-scripts/Coupled_BG_JG_Spinup_CESM2_Production/Model_Version/cesm2.0.0/cime/scripts/create_newcase", line 213, in _main_func
    input_dir=input_dir, driver=driver)
  File "/glade/u/cesm-scripts/liwg/Coupled_BG_JG_Spinup_CESM2_Production/Model_Version/cesm2.0.0/cime/scripts/Tools/../../scripts/lib/CIME/case/case.py", line 1431, in create
    input_dir=input_dir, driver=driver)
  File "/glade/u/cesm-scripts/liwg/Coupled_BG_JG_Spinup_CESM2_Production/Model_Version/cesm2.0.0/cime/scripts/Tools/../../scripts/lib/CIME/case/case.py", line 890, in configure
    charge_account = get_charge_account(machobj)
  File "/glade/u/cesm-scripts/liwg/Coupled_BG_JG_Spinup_CESM2_Production/Model_Version/cesm2.0.0/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 963, in get_charge_account
    return get_project(machobj)
  File "/glade/u/cesm-scripts/liwg/Coupled_BG_JG_Spinup_CESM2_Production/Model_Version/cesm2.0.0/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 911, in get_project
    logger.info("Using project from .cesm_proj: " + project)
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

I haven't looked into this carefully, but at a glance, I'm wondering if this block of code: https://github.com/ESMCI/cime/blob/b78593b3aaeeafc56ec8239905b41820e3ab00c2/scripts/lib/CIME/utils.py#L904-L913 should have a `if project is not None` check, as the other blocks in that function do?

**Comment by billsacks** [comment]
I think the reason this results in a crash despite his explicitly specifying `--project` is because of #2676
