### ISSUE TITLE
SVN error for missing `_svn_loc` using check_input_data script

### ISSUE THREAD

**Issue by pwolfram** [ESMCI/cime#2678]
```
┌─[pwolfram][gr-fe3][/lustre/scratch2/turquoise/pwolfram/tmp_test_particles/E3SM_cases/20180619.GMPAS-IAF.T62_oQU240.grizzly.particles][16:27]
└─▪ ./check_input_data --download
Loading input file list: 'Buildconf/drof.input_data_list'
Loading input file list: 'Buildconf/mpassi.input_data_list'
  Model mpassi missing file mesh = '/lustre/scratch3/turquoise/pwolfram/ACME/input_data/ice/mpas-cice/oQU240/seaice.oQU240km.151209.nc'
  Model mpassi missing file graph72 = '/lustre/scratch3/turquoise/pwolfram/ACME/input_data/ice/mpas-cice/oQU240/mpas-cice.graph.info.151209.part.72'
Loading input file list: 'Buildconf/cpl.input_data_list'
  Model cpl missing file rof2ocn_liq_rmapname = '/lustre/scratch3/turquoise/pwolfram/ACME/input_data/cpl/cpl6/map_rx1_to_oQU240_nn.160527.nc'
  Model cpl missing file atm2ice_fmapname = '/lustre/scratch3/turquoise/pwolfram/ACME/input_data/cpl/gridmaps/T62/map_T62_TO_oQU240_aave.151209.nc'
  Model cpl missing file rof2ocn_ice_rmapname = '/lustre/scratch3/turquoise/pwolfram/ACME/input_data/cpl/cpl6/map_rx1_to_oQU240_nn.160527.nc'
  Model cpl missing file ice2atm_fmapname = '/lustre/scratch3/turquoise/pwolfram/ACME/input_data/cpl/gridmaps/oQU240/map_oQU240_TO_T62_aave.151209.nc'
  Model cpl missing file atm2ice_vmapname = '/lustre/scratch3/turquoise/pwolfram/ACME/input_data/cpl/gridmaps/T62/map_T62_TO_oQU240_patc.151209.nc'
  Model cpl missing file atm2ocn_fmapname = '/lustre/scratch3/turquoise/pwolfram/ACME/input_data/cpl/gridmaps/T62/map_T62_TO_oQU240_aave.151209.nc'
  Model cpl missing file ice2atm_smapname = '/lustre/scratch3/turquoise/pwolfram/ACME/input_data/cpl/gridmaps/oQU240/map_oQU240_TO_T62_aave.151209.nc'
  Model cpl missing file atm2ocn_smapname = '/lustre/scratch3/turquoise/pwolfram/ACME/input_data/cpl/gridmaps/T62/map_T62_TO_oQU240_blin.151209.nc'
  Model cpl missing file atm2ice_smapname = '/lustre/scratch3/turquoise/pwolfram/ACME/input_data/cpl/gridmaps/T62/map_T62_TO_oQU240_blin.151209.nc'
  Model cpl missing file atm2ocn_vmapname = '/lustre/scratch3/turquoise/pwolfram/ACME/input_data/cpl/gridmaps/T62/map_T62_TO_oQU240_patc.151209.nc'
  Model cpl missing file ocn2atm_smapname = '/lustre/scratch3/turquoise/pwolfram/ACME/input_data/cpl/gridmaps/oQU240/map_oQU240_TO_T62_aave.151209.nc'
  Model cpl missing file ocn2atm_fmapname = '/lustre/scratch3/turquoise/pwolfram/ACME/input_data/cpl/gridmaps/oQU240/map_oQU240_TO_T62_aave.151209.nc'
Loading input file list: 'Buildconf/mpaso.input_data_list'
  Model mpaso missing file mesh = '/lustre/scratch3/turquoise/pwolfram/ACME/input_data/ocn/mpas-o/oQU240/ocean.QU.240km.151209.nc'
  Model mpaso missing file ic = '/lustre/scratch3/turquoise/pwolfram/ACME/input_data/ocn/mpas-o/oQU240/ocean.QU.240km.151209.nc'
  Model mpaso missing file graph72 = '/lustre/scratch3/turquoise/pwolfram/ACME/input_data/ocn/mpas-o/oQU240/mpas-o.graph.info.151209.part.72'
Loading input file list: 'Buildconf/datm.input_data_list'
  Model datm missing file domainfile = '/lustre/scratch3/turquoise/pwolfram/ACME/input_data/share/domains/domain.lnd.T62_oQU240.151209.nc'
Checking server https://acme-svn2.ornl.gov/acme-repo/acme/inputdata/ with protocol svn
https://acme-svn2.ornl.gov/acme-repo/acme/inputdata/

Could not connect to svn repo 'https://acme-svn2.ornl.gov/acme-repo/acme/inputdata/'
This is most likely either a credential, proxy, or network issue .
To check connection and store your credential run 'svn ls https://acme-svn2.ornl.gov/acme-repo/acme/inputdata/' and permanently store your password
Loading input file list: 'Buildconf/drof.input_data_list'
Loading input file list: 'Buildconf/mpassi.input_data_list'
  Model mpassi missing file mesh = '/lustre/scratch3/turquoise/pwolfram/ACME/input_data/ice/mpas-cice/oQU240/seaice.oQU240km.151209.nc'
Traceback (most recent call last):
  File "./check_input_data", line 72, in <module>
    _main_func(__doc__)
  File "./check_input_data", line 67, in _main_func
    download=download) else 1)
  File "/lustre/scratch2/turquoise/pwolfram/tmp_test_particles/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/check_input_data.py", line 50, in check_all_input_data
    success = _downloadfromserver(self, input_data_root, data_list_dir)
  File "/lustre/scratch2/turquoise/pwolfram/tmp_test_particles/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/check_input_data.py", line 65, in _downloadfromserver
    input_data_root=input_data_root, data_list_dir=data_list_dir)
  File "/lustre/scratch2/turquoise/pwolfram/tmp_test_particles/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/check_input_data.py", line 207, in check_input_data
    isdirectory=rel_path.endswith(os.sep))
  File "/lustre/scratch2/turquoise/pwolfram/tmp_test_particles/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/check_input_data.py", line 17, in _download_if_in_repo
    if not server.fileexists(rel_path):
  File "/lustre/scratch2/turquoise/pwolfram/tmp_test_particles/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/Servers/svn.py", line 29, in fileexists
    full_url = os.path.join(self._svn_loc, rel_path)
AttributeError: 'SVN' object has no attribute '_svn_loc
```

The contents of `config/e3sm/config_inputdata.xml` is 

```
<?xml version="1.0"?>                                                                                  

<inputdata>
<!-- server precidence is order in this file.  Highest preference at top -->
  <server>
    <protocol>svn</protocol>
    <address>https://acme-svn2.ornl.gov/acme-repo/acme/inputdata/</address>
  </server>
  <server>
    <protocol>svn</protocol>
    <address>https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata/</address>
  </server>

</inputdata>
```

where the lack of a `wget` entry is due to LANL IC firewall issues.                                                                                             

cc @sbrus89, @jgfouca

**Comment by pwolfram** [comment]
I've verified that access to the svn repo is not the issue and for at least one instance of the SVN server class the address is correct.  It appears that there is an additional server instance that has a blank `address` input leading to a blank `_svn_loc` field, implying that a listing or queuing operation may have a bug.

**Comment by pwolfram** [comment]
cc @jonbob -- this is the error we discussed late today.

**Comment by pwolfram** [comment]
The error was resolved by verifying the proxy settings and then doing `svn ls https://acme-svn2.ornl.gov/acme-repo/acme/inputdata/` to permanently store the password.
