### ISSUE TITLE
PR #2759 has caused DAE.f19_f19.A to fail during phase RUN

### ISSUE THREAD

**Issue by dqwu** [ESMCI/cime#2771]
The errors can be reproduced on anlworkstation by running the following cime_developer test:
`./create_test DAE.f19_f19.A --machine=anlworkstation --test-root=****`

Errors were:
```
Exception during run:
ERROR: ERROR: Expected 1 Initial run message(s), 0 found in DAE.f19_f19.A.anlworkstation_gnu.xxxx/run/case2run/da.log.xxxx.gz
Traceback (most recent call last):
  File "scripts/lib/CIME/SystemTests/system_tests_common.py", line 145, in run
    self.run_phase()
  File "scripts/lib/CIME/SystemTests/dae.py", line 155, in run_phase
    "ERROR: Expected {} Initial run message(s), {} found in {}".format(expected_init, found_init, fname))
  File "scripts/lib/CIME/utils.py", line 130, in expect
    raise exc_type(msg)
SystemExit: ERROR: ERROR: Expected 1 Initial run message(s), 0 found in DAE.f19_f19.A.anlworkstation_gnu.xxxx/run/case2run/da.log.xxxx.gz
```
Do we need some settings on anlworkstation to make it work?

**Comment by billsacks** [comment]
Changing the title to reflect the fact that this problem is not just on anlworkstation
