### ISSUE TITLE
T_TestRunRestart failing on hobart

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2796]
With cime master on hobart, I'm getting:

```
test_run_restart (__main__.T_TestRunRestart) ... FAIL
test_run_restart_too_many_fails (__main__.T_TestRunRestart) ... FAIL

======================================================================
FAIL: test_run_restart (__main__.T_TestRunRestart)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./scripts_regression_tests.py", line 1410, in test_run_restart
    self._create_test(["NODEFAIL_P1.f09_g16.X"], test_id=self._baseline_name)
  File "./scripts_regression_tests.py", line 1008, in _create_test
    self._wait_for_tests(test_id, expect_works=(not pre_run_errors and not run_errors))
  File "./scripts_regression_tests.py", line 1017, in _wait_for_tests
    from_dir=self._testroot, expected_stat=expected_stat)
  File "./scripts_regression_tests.py", line 68, in run_cmd_assert_result
    test_obj.assertEqual(stat, expected_stat, msg=msg)
AssertionError:
COMMAND: /home/sacks/cime_master/scripts/Tools/wait_for_tests  *fake_testing_only_20180904_150226/TestStatus
FROM_DIR: /scratch/cluster/sacks/scripts_regression_test.20180904_150220
SHOULD HAVE WORKED, INSTEAD GOT STAT 100
OUTPUT: Test 'NODEFAIL_P1.f09_g16.X.hobart_intel' finished with status 'FAIL'
    Path: NODEFAIL_P1.f09_g16.X.hobart_intel.fake_testing_only_20180904_150226/TestStatus
ERRPUT:


======================================================================
FAIL: test_run_restart_too_many_fails (__main__.T_TestRunRestart)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./scripts_regression_tests.py", line 1429, in test_run_restart_too_many_fails
    self.assertTrue(os.path.exists(fail_sentinel), msg="Missing %s" % fail_sentinel)
AssertionError: Missing /scratch/cluster/sacks/scripts_regression_test.20180904_150220/NODEFAIL_P1.f09_g16.X.hobart_intel.fake_testing_only_20180904_150825/run/FAIL_SENTINEL
```

**Comment by billsacks** [comment]
Closing since we no longer run on hobart.
