### ISSUE TITLE
Zero size inputdata file created when file isn't availble from the data repo.

### ISSUE THREAD

**Issue by fischer-ncar** [ESMCI/cime#2910]
I've run into a problem where an inputdata file of 0 size is created.  This happens when the file needs to be
downloaded from the data repo, but it isn't available.  

Reproduce the problem using cesm2_1_alpha01e.  Change your DIN_LOC_ROOT, then.
./create_test ERS_Ld5.f09_g17.B1PCTcmip6.cheyenne_intel.allactive-defaultio_min

inputdata/atm/waccm/lb/LBC_CMIP6_1pctCO2_y1-165_GlobAnnAvg_0p5degLat_c180929.nc
Will be created with a size of 0.

`   Model cam missing file flbc_file = '/glade/scratch/fischer/inputdata/atm/waccm/lb/LBC_CMIP6_1pctCO2_y1-165_GlobAnnAvg_0p5degLat_c180929.nc'
Trying to download file: 'atm/waccm/lb/LBC_CMIP6_1pctCO2_y1-165_GlobAnnAvg_0p5degLat_c180929.nc' to path '/glade/scratch/fischer/inputdata/atm/waccm/lb/LBC_CMIP6_1pctCO2_y1-165_GlobAnnAvg_0p5degLat_c180929.nc'
Traceback (most recent call last):
  File "./check_input_data", line 72, in <module>
    _main_func(__doc__)
  File "./check_input_data", line 67, in _main_func
    download=download) else 1)
  File "/gpfs/u/home/fischer/code/cesm2_1_alpha01e/cime/scripts/Tools/../../scripts/lib/CIME/case/check_input_data.py", line 50, in check_all_input_data
    success = _downloadfromserver(self, input_data_root, data_list_dir)
  File "/gpfs/u/home/fischer/code/cesm2_1_alpha01e/cime/scripts/Tools/../../scripts/lib/CIME/case/check_input_data.py", line 65, in _downloadfromserver
    input_data_root=input_data_root, data_list_dir=data_list_dir)
  File "/gpfs/u/home/fischer/code/cesm2_1_alpha01e/cime/scripts/Tools/../../scripts/lib/CIME/case/check_input_data.py", line 209, in check_input_data
    isdirectory=rel_path.endswith(os.sep))
  File "/gpfs/u/home/fischer/code/cesm2_1_alpha01e/cime/scripts/Tools/../../scripts/lib/CIME/case/check_input_data.py", line 37, in _download_if_in_repo
    return server.getfile(rel_path, full_path)
  File "/gpfs/u/home/fischer/code/cesm2_1_alpha01e/cime/scripts/Tools/../../scripts/lib/CIME/Servers/wget.py", line 35, in getfile
    logging.warning("wget failed with output: {} and errput {}\n".format(output, errput))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 147: ordinal not in range(128)
`

**Comment by jedwards4b** [comment]
Ideally an md5 checksum should be performed on the downloaded file.
