### ISSUE TITLE
cime_developer tests failed on anlworkstation

### ISSUE THREAD

**Issue by dqwu** [ESMCI/cime#3033]
The errors can be reproduced on anlworkstation by running a single cime_developer test:
`./create_test DAE.ww3a.ADWAV --machine=anlworkstation --test-root=****`

Errors were:
```
        Traceback (most recent call last):
          File "./case.submit", line 108, in <module>
            _main_func(__doc__)
          File "./case.submit", line 105, in _main_func
            mail_user=mail_user, mail_type=mail_type, batch_args=batch_args)
          File "scripts/lib/CIME/case/case_submit.py", line 191, in submit
            custom_success_msg_functor=verbatim_success_msg)
          File "scripts/lib/CIME/utils.py", line 1702, in run_and_log_case_status
            rv = func()
          File "scripts/lib/CIME/case/case_submit.py", line 189, in <lambda>
            batch_args=batch_args)
          File "scripts/lib/CIME/case/case_submit.py", line 120, in _submit
            case.check_case()
          File "scripts/lib/CIME/case/case_submit.py", line 205, in check_case
            self.check_all_input_data()
          File "scripts/lib/CIME/case/check_input_data.py", line 159, in check_all_input_data
            chksum_file)
          File "scripts/lib/CIME/case/check_input_data.py", line 37, in _download_checksum_file
            success = server.getfile(rel_path, new_file)
          File "scripts/lib/CIME/Servers/wget.py", line 31, in getfile
            full_url = os.path.join(self._server_loc, rel_path)
          File "/usr/lib/python2.7/posixpath.py", line 75, in join
            if b.startswith('/'):
        AttributeError: 'NoneType' object has no attribute 'startswith'
```
This test passed before. Is this caused by missing input files requierd by latest CIME?
Looks like CIME is not handling the case where there is no file to download (None)?

**Comment by jgfouca** [comment]
I'll take a look at it.

**Comment by jedwards4b** [comment]
How would it get there without a filename?
