### ISSUE TITLE
Improve support for --resubmit-immediate option

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#3162]
Texas computing (TACC) does not allow resubmit from the compute nodes and wants only to support the --resubmit-immediate option of case.submit   A number of our system tests use the resubmit mechanism and know nothing about --resubmit-immediate.   Can we modify system tests to work with this mechanism?

**Comment by jedwards4b** [comment]
I try to run an ERR test as follows:
./create_test ERR.f09_g16.X --no-run
cd $TESTDIR
./case.submit --resubmit-immediate

This results in:
```
2019-08-06 13:41:23: Exception during run:
[Errno 2] No such file or directory: '/scratch/cluster/jedwards/archive/ERR.f09_g16.X.izumi_intel.20190806_133737_vny302/rest'
Traceback (most recent call last):
  File "/home/jedwards/cesm2_x_alpha/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_common.py", line 143, in run
    self.run_phase()
  File "/home/jedwards/cesm2_x_alpha/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_compare_two.py", line 253, in run_phase
    self._case_two_custom_prerun_action()
  File "/home/jedwards/cesm2_x_alpha/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/err.py", line 35, in _case_two_custom_prerun_action
    restart_list = ls_sorted_by_mtime(rest_root)
  File "/home/jedwards/cesm2_x_alpha/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 1598, in ls_sorted_by_mtime
    return list(sorted(os.listdir(path), key=mtime))
OSError: [Errno 2] No such file or directory: '/scratch/cluster/jedwards/archive/ERR.f09_g16.X.izumi_intel.20190806_133737_vny302/rest'
```
in the first run job - why is it doing case two stuff here?
