### ISSUE TITLE
case.setup refuses to fix corrupted env_mach_specfic.xml

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#3459]
Introduced with #3449 if the env_mach_specific.xml file in the case is corrupted or missing 
case.setup --reset will not run
```
 ./case.setup --reset

Successfully cleaned env_mach_specific.xml
Successfully cleaned Macros.make
Traceback (most recent call last):
  File "./case.setup", line 62, in <module>
    _main_func(__doc__)
  File "./case.setup", line 59, in _main_func
    case.case_setup(clean=clean, test_mode=test_mode, reset=reset)
  File "/glade/work/jedwards/sandboxes/cesm2_x_nuopc/cime/scripts/Tools/../../scripts/lib/CIME/case/case.py", line 195, in __exit__
    self.flush()
  File "/glade/work/jedwards/sandboxes/cesm2_x_nuopc/cime/scripts/Tools/../../scripts/lib/CIME/case/case.py", line 270, in flush
    env_file.write(force_write=flushall)
  File "/glade/work/jedwards/sandboxes/cesm2_x_nuopc/cime/scripts/Tools/../../scripts/lib/CIME/XML/generic_xml.py", line 325, in write
    self.check_timestamp()
  File "/glade/work/jedwards/sandboxes/cesm2_x_nuopc/cime/scripts/Tools/../../scripts/lib/CIME/XML/generic_xml.py", line 317, in check_timestamp
    timestamp_file  = os.path.getmtime(self.filename)
  File "/usr/lib64/python2.7/genericpath.py", line 62, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: '/glade/scratch/jedwards/SMS_D_Ln5_Vnuopc.f10_f10_mg37.QPC6.cheyenne_intel.cam-outfrq9s.20200317_164905_wiaa4z/env_mach_specific.xml'
```

**Comment by jedwards4b** [comment]
@jgfouca have you looked into this at all?   I realize that I frequently want to change the module commands or env variables for a particular case by editing env_mach_specific.xml and I can't do this anymore because it is being overwritten - can we add a flag to keep the old behavior?

**Comment by jgfouca** [comment]
Hey @jedwards4b , this dropped-off my radar, sry! I will look at it this afternoon.
