### ISSUE TITLE
Archive tests failing after component name change

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#3704]
I'm in the process of changing "clm" to "elm" in E3SM and have everything working except the SHORT_TERM_ARCHIVER part of even an SMS test.  The other parts of the test run fine (all files are created).

The error message is below.  I've renamed "compname" in config_archive.xml to "elm" but all the history files still have "clm2" in them.   Is there an assumption somewhere that the "compname" string is in the file name?

```
2020-09-12 01:32:28: Exception during SHORT_TERM_ARCHIVER:
ERROR: Failed to move file casename.clm2.h0.1976-01-01-00000.nc to archive
Traceback (most recent call last):
  File "/gpfs/fs1/home/jacob/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_common.py", line 397, in _phase_modifying_call
    function()
  File "/gpfs/fs1/home/jacob/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_common.py", line 349, in _st_archive_case_test
    result = self._case.test_env_archive()
  File "/gpfs/fs1/home/jacob/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/case_st_archive.py", line 867, in test_env_archive
    _check_disposition(testdir)
  File "/gpfs/fs1/home/jacob/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/case_st_archive.py", line 896, in _check_disposition
    "Failed to move file {} to archive".format(_file))
  File "/gpfs/fs1/home/jacob/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 137, in expect
    raise exc_type(msg)
CIMEError: ERROR: Failed to move file casename.clm2.h0.1976-01-01-00000.nc to archive
```

**Comment by ekluzek** [comment]
I can't say where this assumption is. But, I can confirm I had the same thing happen with updating to "ctsm". The archiver needed to see that the name was component name with possibly a one digit version at the end (more than one digit doesn't work either). But, it does seem to need to match the component name. This also caused problems in some of the standard testing, I think likely because of this.

If there's any loops that go over "component name" I'm guessing that might be the problem.

**Comment by ekluzek** [comment]
By the way, you might want to look at PR #3664 just to see what I needed for ctsm, as that might help you for elm.

**Comment by rljacob** [comment]
Thanks @ekluzek.  I had forgotten about the Makefile.

I found some lines like this in case_st_archive.py
```
     if compname == 'drv':
         compname = 'cpl'
```

I tried doing the same thing for elm:clm but that didn't help.

**Comment by rljacob** [comment]
Another aspect of this fail is there is no "lnd" subdirectory under env_archive_test/archive

But when I finally change the output files to have "elm" instead of "clm" and remove my hack to case_st_archive.py, then it works!

**Comment by rljacob** [comment]
Closing and moving discussion to #3710
