### ISSUE TITLE
Errors from scripts_regression_tests when running a subset of tests

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3768]
When running a subset of tests, I'm getting an error in the cleanup function:

Here is the end of the output from running `./scripts_regression_tests.py A_RunUnitTests` on cheyenne:

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "./scripts_regression_tests.py", line 3508, in cleanup
    files = os.listdir(TEST_ROOT)
OSError: [Errno 2] No such file or directory: '/glade/scratch/sacks/scripts_regression_test.20201104_122743'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "./scripts_regression_tests.py", line 3508, in cleanup
    files = os.listdir(TEST_ROOT)
OSError: [Errno 2] No such file or directory: '/glade/scratch/sacks/scripts_regression_test.20201104_122743'
```

My guess is that the given directory is only created when running certain tests, and the cleanup function needs to be more robust to the possibility that this directory may not have been created.

**Comment by jgfouca** [comment]
Assigning @WesCoomber since this is a good beginner issue.
