### ISSUE TITLE
compare_test_results: logfile_name can be undefined

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3814]
In some circumstances, logfile_name can be undefined when running compare_test_results.

This happened to me when running like this:

```
./compare_test_results --hist-only -b ctsm5.1.dev019 --baseline-root $scratch/cesm_baselines -r /scratch/cluster/sacks/tests_1222-131830iz -t 1222-131830iz

SKIP ERS_Ld5.f10_f10_musgs.I2000Clm50BgcCropRtm.izumi_nag.rtm-default BASELINE Run phase did not pass

Traceback (most recent call last):
  File "./compare_test_results", line 105, in <module>
    _main_func(__doc__)
  File "./compare_test_results", line 99, in _main_func
    success = compare_test_results(baseline_name, baseline_root, test_root, compiler, test_id, compare_tests, namelists_only, hist_only)
  File "/home/sacks/ctsm_code/ctsm/cime/scripts/Tools/../../scripts/lib/CIME/compare_test_results.py", line 158, in compare_test_results
    append_status_cprnc_log(brief_result, logfile_name, test_dir)
UnboundLocalError: local variable 'logfile_name' referenced before assignment
```

It looks like logfile_name is only defined when it finds a test that actually needs comparison (so not a skipped test like this one), yet it is referenced for all tests in the append_status_cprnc_log line.

I'm not positive,  but I think this error was introduced in #2079

@jgfouca

**Comment by jgfouca** [comment]
thx @billsacks , I will fix
