### ISSUE TITLE
PR #3977 generates error

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#3983]
After merging #3977 I am getting the following unit test error:

test_unittests (__main__.A_RunUnitTests) ... ........................E....................................................
======================================================================
ERROR: test__submit (CIME.tests.test_case.TestCaseSubmit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/lib/python3.7/unittest/mock.py", line 1256, in patched
    return func(*args, **keywargs)
  File "/glade/work/jedwards/sandboxes/cesm2_x_alpha/cime/scripts/tests/../lib/CIME/tests/test_case.py", line 23, in test__submit
    case_submit._submit(case, chksum=True) # pylint: disable=protected-access
  File "/glade/work/jedwards/sandboxes/cesm2_x_alpha/cime/scripts/tests/../lib/CIME/case/case_submit.py", line 72, in _submit
    unlock_file(os.path.basename(env_batch.filename))
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/lib/python3.7/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not MagicMock

**Comment by jasonb5** [comment]
@jedwards4b It looks like this only appears with py37, should we cover this version in the GitHub action workflow?
