### ISSUE TITLE
Run a test on Theta with a walltime less than the default queue min walltime

### ISSUE THREAD

**Issue by dqwu** [ESMCI/cime#3993]
According to https://alcf.anl.gov/support-center/theta/job-scheduling-policy-theta:
On Theta, there is a minimum job time of thirty (00:30:00) minutes for the default queue.

This can be confirmed with the following commands on a login node of Theta:
```
qsub -A ClimateEnergy_4 -t 00:15:00 -n 128 -q default -I
Connecting to thetamom3 for interactive qsub...
Job routed to queue "default".
No handlers could be found for logger "Proxy"
<Fault 1001: "Walltime less than the 'default' queue min walltime of 00:30:00\n">
Connection to thetamom3 closed.
```
Run the following test on Theta with an explicit --walltime argument which is less than 30 mins
`create_test ERP_Ld3.ne30_oECv3.A_WCYCL1850S.theta_intel.allactive-pioroot1 --project ClimateEnergy_4 --walltime 00:15:00`
The error messages will be something like:
```
        CIME.utils.CIMEError: ERROR: Command: '/projects/ccsm/acme/tools/cobalt/dsub -A ClimateEnergy_4 -t 00:15:00 -n 129 -q default --mode script --env ARGS_FOR_SCRIPT='--skip-preview-namelist' .case.test' failed with error 'Job routed to queue "default".
        No handlers could be found for logger "Proxy"
        <Fault 1001: "Walltime less than the 'default' queue min walltime of 00:30:00\n">' from dir 'ERP_Ld3.ne30_oECv3.A_WCYCL1850S.theta_intel.allactive-pioroot1.20210609_041934_vpfsi6'
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "./case.submit", line 126, in <module>
            _main_func(__doc__)
          File "./case.submit", line 123, in _main_func
            mail_user=mail_user, mail_type=mail_type, batch_args=batch_args, workflow=workflow)
          File "E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/case_submit.py", line 208, in submit
            is_batch=is_batch)
          File "E3SM/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 1811, in run_and_log_case_status
            custom_success_msg = custom_success_msg_functor(rv) if custom_success_msg_functor else None
          File "E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/case_submit.py", line 207, in <lambda>
            custom_success_msg_functor=lambda x: x.split(":")[-1],
        AttributeError: 'NoneType' object has no attribute 'split'
```
While "Fault 1001" returned by dsub command is as expected, there are two others issues to take a look at:
1) Before calling the job submission command, CIME might consider printing out a warning (or an error) on user-specified 15-min walltime, or resetting it to 30-min automatically. Actually, in E3SM/cime_config/machines/config_batch.xml, walltimemin is defined as 30-min:
```
    <batch_system MACH="theta" type="cobalt_theta">
      <queues>
        <queue walltimemax="01:00:00" nodemin="1" nodemax="8" strict="true">debug-cache-quad</queue>
        <queue walltimemin="00:30:00" walltimemax="03:00:00" nodemin="128" nodemax="255"  strict="true">default</queue>
        <queue walltimemin="00:30:00" walltimemax="06:00:00" nodemin="256" nodemax="383"  strict="true">default</queue>
        <queue walltimemin="00:30:00" walltimemax="09:00:00" nodemin="384" nodemax="639"  strict="true">default</queue>
        <queue walltimemin="00:30:00" walltimemax="12:00:00" nodemin="640" nodemax="801"  strict="true">default</queue>
        <queue walltimemin="00:30:00" walltimemax="24:00:00" nodemin="802" strict="true" default="true">default</queue>
      </queues>
    </batch_system>
```
It seems that this higher level check is missing: "-t 00:15:00" is still passed to the dsub command on Theta.

2) The Python exception (AttributeError: 'NoneType' object has no attribute 'split') might also be fixed when dsub command returns an error.

**Comment by jasonb5** [comment]
@dqwu Thanks for writing this up. I'll take a look and should have a fix soon.
