### ISSUE TITLE
CIME errors with git worktree

### ISSUE THREAD

**Issue by xylar** [ESMCI/cime#4036]
I believe I have been able to use E3SM just fine in the past from a git worktree.  Here is a simplified example workflow on Chrysalis:
```
git clone git@github.com:E3SM-Project/E3SM.git
cd E3SM
git worktree add ../test
cd ../test
git submodule update --init --recursive
cd cime/scripts/
./create_test --walltime 01:00:00 SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel --wait
```

The error I'm seeing is:
```
No project info available
create_test will do up to 1 tasks simultaneously
create_test will use up to 160 cores simultaneously
Creating test directory /lcrc/group/e3sm/ac.xylar/scratch/chrys/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel.20210712_130312_hpod6c
RUNNING TESTS:
  SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel
Starting CREATE_NEWCASE for test SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel with 1 procs
Finished CREATE_NEWCASE for test SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel in 0.975402 seconds (PASS)
Starting XML for test SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel with 1 procs
Finished XML for test SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel in 0.189899 seconds (PASS)
Starting SETUP for test SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel with 1 procs
Finished SETUP for test SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel in 3.179292 seconds (PASS)
Starting SHAREDLIB_BUILD for test SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel with 1 procs
Finished SHAREDLIB_BUILD for test SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel in 163.753454 seconds (PASS)
Starting MODEL_BUILD for test SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel with 6 procs
Finished MODEL_BUILD for test SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel in 904.674959 seconds (FAIL). [COMPLETED 1 of 1]
    Case dir: /lcrc/group/e3sm/ac.xylar/scratch/chrys/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel.20210712_130312_hpod6c
    Errors were:
        Building test for SMS in directory /lcrc/group/e3sm/ac.xylar/scratch/chrys/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel.20210712_130312_hpod6c
        Traceback (most recent call last):
          File "/lcrc/group/e3sm/ac.xylar/scratch/chrys/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel.20210712_130312_hpod6c/./case.build", line 167, in <module>
            _main_func(__doc__)
          File "/lcrc/group/e3sm/ac.xylar/scratch/chrys/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel.20210712_130312_hpod6c/./case.build", line 156, in _main_func
            success = test.build(sharedlib_only=sharedlib_only, model_only=model_only, ninja=ninja, dry_run=dry_run, separate_builds=separate_builds)
          File "/gpfs/fs1/home/ac.xylar/e3sm_work/test/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_common.py", line 95, in build
            self.build_phase(sharedlib_only=(phase_name==SHAREDLIB_BUILD_PHASE),
          File "/gpfs/fs1/home/ac.xylar/e3sm_work/test/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_common.py", line 124, in build_phase
            self.build_indv(sharedlib_only=sharedlib_only, model_only=model_only)
          File "/gpfs/fs1/home/ac.xylar/e3sm_work/test/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_common.py", line 131, in build_indv
            build.case_build(self._caseroot, case=self._case,
          File "/gpfs/fs1/home/ac.xylar/e3sm_work/test/cime/scripts/Tools/../../scripts/lib/CIME/build.py", line 793, in case_build
            return run_and_log_case_status(functor, cb, caseroot=caseroot)
          File "/gpfs/fs1/home/ac.xylar/e3sm_work/test/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 1810, in run_and_log_case_status
            rv = func()
          File "/gpfs/fs1/home/ac.xylar/e3sm_work/test/cime/scripts/Tools/../../scripts/lib/CIME/build.py", line 786, in <lambda>
            functor = lambda: _case_build_impl(caseroot, case, sharedlib_only, model_only, buildlist,
          File "/gpfs/fs1/home/ac.xylar/e3sm_work/test/cime/scripts/Tools/../../scripts/lib/CIME/build.py", line 751, in _case_build_impl
            post_build(case, logs, build_complete=not (buildlist or sharedlib_only),
          File "/gpfs/fs1/home/ac.xylar/e3sm_work/test/cime/scripts/Tools/../../scripts/lib/CIME/build.py", line 772, in post_build
            save_build_provenance_sub(case, lid=lid)
          File "/gpfs/fs1/home/ac.xylar/e3sm_work/test/cime/scripts/Tools/../../scripts/lib/CIME/provenance.py", line 199, in save_build_provenance
            _save_build_provenance_e3sm(case, lid)
          File "/gpfs/fs1/home/ac.xylar/e3sm_work/test/cime/scripts/Tools/../../scripts/lib/CIME/provenance.py", line 115, in _save_build_provenance_e3sm
            _record_git_provenance(srcroot, exeroot, lid)
          File "/gpfs/fs1/home/ac.xylar/e3sm_work/test/cime/scripts/Tools/../../scripts/lib/CIME/provenance.py", line 88, in _record_git_provenance
            safe_copy(config_src, config_prov, preserve_meta=False)
          File "/gpfs/fs1/home/ac.xylar/e3sm_work/test/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 937, in safe_copy
            file_util.copy_file(src_path, tgt_path, preserve_mode=preserve_meta, preserve_times=preserve_meta)
          File "/home/ac.xylar/chrysalis/miniconda3/lib/python3.9/distutils/file_util.py", line 104, in copy_file
            raise DistutilsFileError(
        distutils.errors.DistutilsFileError: can't copy '/gpfs/fs1/home/ac.xylar/e3sm_work/test/.git/config': doesn't exist or not a regular file

Waiting for tests to finish
FAIL SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel (phase MODEL_BUILD)
    Case dir: /lcrc/group/e3sm/ac.xylar/scratch/chrys/SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel.20210712_130312_hpod6c
```

CIME seems to be expecting to find a `.git/config` file, but a git worktree has a `.git` file, rather than a `.git` directory.  The use of `git woktree` is pretty central to my workflow, so this makes E3SM development a bit challenging for me.

**Comment by jedwards4b** [comment]
This seems to be an issue with save_build_provenance_e3sm and so I have marked it e3sm only.

**Comment by xylar** [comment]
Thanks @jedwards4b.  Am I right that it's a CIME issue, rather than one for the E3SM repo?

**Comment by jedwards4b** [comment]
@xylar yes - I think so.

**Comment by billsacks** [comment]
@xylar I also use git worktree heavily and haven't noticed any issues recently, so also suspect this is e3sm-specific (unless there's a recent issue that I haven't run into).

**Comment by jgfouca** [comment]
@billsacks , @xylar , this is an e3sm-specific issue in CIME. We want to, at some point, move more of the e3sm-specific stuff in CIME into E3SM. We haven't done this yet, so our e3sm provenance still lives in CIME.
