### ISSUE TITLE
replay.sh should not cause fail if it cannot write 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#4050]
I was trying to examine another users case:
```
./pelayout
Traceback (most recent call last):
  File "./pelayout", line 244, in <module>
    _main_func(__doc__)
  File "./pelayout", line 230, in _main_func
    with Case(caseroot, record=True) as case:
  File "/glade/work/turuncu/TESTING/CESM_newalarm/cime/scripts/Tools/../../scripts/lib/CIME/case/case.py", line 104, in __init__
    self.record_cmd()
  File "/glade/work/turuncu/TESTING/CESM_newalarm/cime/scripts/Tools/../../scripts/lib/CIME/case/case.py", line 1683, in record_cmd
    with open(os.path.join(caseroot, "replay.sh"), "a") as fd:
PermissionError: [Errno 13] Permission denied: '/glade/scratch/turuncu/IRT_N3_PM3_Ld7_Vnuopc.f19_g17.BHIST.cheyenne_intel.allactive-defaultio.20210719_160023_50zo6w/replay.sh'
```
I think that instead of failing it should just print a message that the script is not writable

**Comment by jasonb5** [comment]
This was fixed in #4053.
