### ISSUE TITLE
Replace deprecated distutils module.

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#4324]
@alperaltuntas  I am getting this error on gust - can you help?
```
Traceback (most recent call last):
  File "/glade/work/jedwards/sandboxes/cesm2_x_alpha/cime/CIME/tests/test_unit_paramgen.py", line 372, in test_single_key_val_guard
    pg = ParamGen.from_xml_nml(temp.name)
  File "/glade/work/jedwards/sandboxes/cesm2_x_alpha/cime/CIME/ParamGen/paramgen.py", line 154, in from_xml_nml
    xmllint_cmd, shell=True, capture_output=True, text=True, check=True
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

**Comment by jedwards4b** [comment]
python on gust is in version 3.6.15 - if this is too old @alperaltuntas can you add a minimum version message and exit?

**Comment by alperaltuntas** [comment]
This import statement is used in multiple CIME modules, so I doubt this is strictly a ParamGen issue. And it seems like a broader solution should be agreed upon for all modules.

```
grep -rin "distutils.spawn import find_executable" .
./tools/load_balancing_tool/optimize_model.py:358:        from distutils.spawn import find_executable
./CIME/XML/generic_xml.py:11:from distutils.spawn import find_executable
./CIME/code_checker.py:23:from distutils.spawn import find_executable
./CIME/Tools/code_checker:15:from distutils.spawn import find_executable
./CIME/Tools/xmlconvertors/grid_xml_converter.py:28:from distutils.spawn import find_executable
./CIME/Tools/xmlconvertors/config_pes_converter.py:20:from distutils.spawn import find_executable
./CIME/Servers/__init__.py:2:from distutils.spawn import find_executable
./CIME/wait_for_tests.py:6:from distutils.spawn import find_executable
./CIME/ParamGen/paramgen.py:139:        from distutils.spawn import find_executable
```

**Comment by jedwards4b** [comment]
Okay I've changed the title of the issue.
The distutils package is deprecated and slated for removal in Python 3.12
