### ISSUE TITLE
bug in customize_module_spec

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#4420]
When I run from create_test I am getting:
```
 ./create_test SMS.mpasa120_mpasa120.FHS94.gust_nvhpc --debug
RUN: /usr/bin/xmllint --xinclude --noout --schema /glade/work/jedwards/sandboxes/EarthWorks/cime/CIME/data/config/xml_schemas/entry_id.xsd /glade/work/jedwards/sandboxes/EarthWorks/cime/CIME/data/config/cesm/config_files.xml
FROM: /glade/work/jedwards/sandboxes/EarthWorks/cime/scripts
  errput: /glade/work/jedwards/sandboxes/EarthWorks/cime/CIME/data/config/cesm/config_files.xml validates

RUN: /usr/bin/xmllint --xinclude --noout --schema /glade/work/jedwards/sandboxes/EarthWorks/cime/CIME/data/config/xml_schemas/config_machines.xsd /glade/work/jedwards/sandboxes/EarthWorks/ccs_config/machines/config_machines.xml
FROM: /glade/work/jedwards/sandboxes/EarthWorks/cime/scripts
  errput: /glade/work/jedwards/sandboxes/EarthWorks/ccs_config/machines/config_machines.xml validates

Testnames: ['SMS.mpasa120_mpasa120.FHS94.gust_nvhpc']
Using project from env PROJECT: P93300606
create_test will do up to 1 tasks simultaneously
create_test will use up to 160 cores simultaneously
Creating test directory /glade/gust/scratch/jedwards/SMS.mpasa120_mpasa120.FHS94.gust_nvhpc.20230504_104601_dlxjrj
RUNNING TESTS:
  SMS.mpasa120_mpasa120.FHS94.gust_nvhpc
Starting CREATE_NEWCASE for test SMS.mpasa120_mpasa120.FHS94.gust_nvhpc with 1 procs
RUN: /glade/u/apps/gust/23.04/opt/bin/python3 /glade/work/jedwards/sandboxes/EarthWorks/cime/CIME/scripts/create_newcase.py --case /glade/gust/scratch/jedwards/SMS.mpasa120_mpasa120.FHS94.gust_nvhpc.20230504_104601_dlxjrj --res mpasa120_mpasa120 --compset FHS94 --test --machine gust --compiler nvhpc --project P93300606  --workflow default --srcroot /glade/work/jedwards/sandboxes/EarthWorks
FROM: /glade/work/jedwards/sandboxes/EarthWorks/cime/scripts
  stat: 1

  output: customize_path=/glade/work/jedwards/sandboxes/EarthWorks/cime_config/customize

  errput: Traceback (most recent call last):
  File "/glade/work/jedwards/sandboxes/EarthWorks/cime/CIME/scripts/create_newcase.py", line 459, in <module>
    _main_func(__doc__)
  File "/glade/work/jedwards/sandboxes/EarthWorks/cime/CIME/scripts/create_newcase.py", line 385, in _main_func
    ) = parse_command_line(sys.argv, cimeroot, description)
  File "/glade/work/jedwards/sandboxes/EarthWorks/cime/CIME/scripts/create_newcase.py", line 33, in parse_command_line
    config = Config.load(customize_path)
  File "/glade/work/jedwards/sandboxes/EarthWorks/cime/CIME/config.py", line 224, in load
    customize_module_spec = importlib.machinery.ModuleSpec("cime_customize", None)
AttributeError: module 'importlib' has no attribute 'machinery'

Finished CREATE_NEWCASE for test SMS.mpasa120_mpasa120.FHS94.gust_nvhpc in 0.433541 seconds (FAIL). [COMPLETED 1 of 1]
    Case dir: /glade/gust/scratch/jedwards/SMS.mpasa120_mpasa120.FHS94.gust_nvhpc.20230504_104601_dlxjrj
    Errors were:
        Traceback (most recent call last):
          File "/glade/work/jedwards/sandboxes/EarthWorks/cime/CIME/scripts/create_newcase.py", line 459, in <module>
            _main_func(__doc__)
          File "/glade/work/jedwards/sandboxes/EarthWorks/cime/CIME/scripts/create_newcase.py", line 385, in _main_func
            ) = parse_command_line(sys.argv, cimeroot, description)
          File "/glade/work/jedwards/sandboxes/EarthWorks/cime/CIME/scripts/create_newcase.py", line 33, in parse_command_line
            config = Config.load(customize_path)
          File "/glade/work/jedwards/sandboxes/EarthWorks/cime/CIME/config.py", line 224, in load
            customize_module_spec = importlib.machinery.ModuleSpec("cime_customize", None)
        AttributeError: module 'importlib' has no attribute 'machinery'

Waiting for tests to finish
FAIL SMS.mpasa120_mpasa120.FHS94.gust_nvhpc (phase CREATE_NEWCASE)
    Case dir: /glade/gust/scratch/jedwards/SMS.mpasa120_mpasa120.FHS94.gust_nvhpc.20230504_104601_dlxjrj
Due to presence of batch system, create_test will exit before tests are complete.
To force create_test to wait for full completion, use --wait
test-scheduler took 1.6219749450683594 seconds

```
However if I take the same create_newcase command and run from the command line, it works fine.   Any ideas?
```
 PYTHONPATH=$PYTHONPATH:~/sandboxes/EarthWorks/cime/:~/sandboxes/EarthWorks/cime/CIME/Tools /glade/u/apps/gust/23.04/opt/bin/python3 /glade/work/jedwards/sandboxes/EarthWorks/cime/CIME/scripts/create_newcase.py --case /glade/gust/scratch/jedwards/SMS.mpasa120_mpasa120.FHS94.gust_nvhpc.20230504_104242_m06gdh --res mpasa120_mpasa120 --compset FHS94 --machine gust --compiler nvhpc --project P93300606  --workflow default --srcroot /glade/work/jedwards/sandboxes/EarthWorks --run-unsupported
customize_path=/glade/work/jedwards/sandboxes/EarthWorks/cime_config/customize
Compset longname is 2000_CAM%HS94_SLND_SICE_SOCN_SROF_SGLC_SWAV
Compset specification file is /glade/work/jedwards/sandboxes/EarthWorks/components/cam//cime_config/config_compsets.xml
Automatically adding SESP to compset
Compset forcing is 1972-2004
ATM component is CAM simplified and non-versioned physics :CAM dry Held-Suarez forcing (Held and Suarez (1994)):
LND component is Stub land component
ICE component is Stub ice component
OCN component is Stub ocn component
ROF component is Stub river component
GLC component is Stub glacier (land ice) component
WAV component is Stub wave component
ESP component is Stub external system processing (ESP) component
Pes     specification file is /glade/work/jedwards/sandboxes/EarthWorks/components/cam//cime_config/config_pes.xml
Machine is gust
Pes setting: grid          is a%mpasa120_l%null_oi%null_r%null_g%null_w%null_z%null_m%gx1v7 
Pes setting: compset       is 2000_CAM%HS94_SLND_SICE_SOCN_SROF_SGLC_SWAV_SESP 
Pes setting: tasks       is {'NTASKS_ATM': -1, 'NTASKS_LND': -1, 'NTASKS_ROF': -1, 'NTASKS_ICE': -1, 'NTASKS_OCN': -1, 'NTASKS_GLC': -1, 'NTASKS_WAV': -1, 'NTASKS_CPL': -1} 
Pes setting: threads     is {'NTHRDS_ATM': 1, 'NTHRDS_LND': 1, 'NTHRDS_ROF': 1, 'NTHRDS_ICE': 1, 'NTHRDS_OCN': 1, 'NTHRDS_GLC': 1, 'NTHRDS_WAV': 1, 'NTHRDS_CPL': 1} 
Pes setting: rootpe      is {'ROOTPE_ATM': 0, 'ROOTPE_LND': 0, 'ROOTPE_ROF': 0, 'ROOTPE_ICE': 0, 'ROOTPE_OCN': 0, 'ROOTPE_GLC': 0, 'ROOTPE_WAV': 0, 'ROOTPE_CPL': 0} 
Pes setting: pstrid      is {} 
Pes other settings: {}
Pes comments: none
setting additional fields from config_pes: {}
 Compset is: 2000_CAM%HS94_SLND_SICE_SOCN_SROF_SGLC_SWAV_SESP 
 Grid is: a%mpasa120_l%null_oi%null_r%null_g%null_w%null_z%null_m%gx1v7 
 Components in compset are: ['cam', 'slnd', 'sice', 'socn', 'srof', 'sglc', 'swav', 'sesp'] 
No charge_account info available, using value from PROJECT
cesm model version found: cesm2_3_beta12
Batch_system_type is pbs
job is case.run USER_REQUESTED_WALLTIME None USER_REQUESTED_QUEUE None WALLTIME_FORMAT %H:%M:%S
job is case.st_archive USER_REQUESTED_WALLTIME None USER_REQUESTED_QUEUE None WALLTIME_FORMAT %H:%M:%S
 Creating Case directory /glade/gust/scratch/jedwards/SMS.mpasa120_mpasa120.FHS94.gust_nvhpc.20230504_104242_m06gdh
```

**Comment by jgfouca** [comment]
Looks like it's a problem with your python:
```
importlib.machinery.ModuleSpec("cime_customize", None)
AttributeError: module 'importlib' has no attribute 'machinery'
```

Specifically, importlib is missing the machinery function. What version of python are you using?

**Comment by jgfouca** [comment]
Oh, and since it happens in create_test but not create_newcase, I assume the machine environment in config_machines.xml is what is loading the old python.

**Comment by jedwards4b** [comment]
From the command line I have: python 3.10.8
In config.py I added:
```
+        try:
+            customize_module_spec = importlib.machinery.ModuleSpec("cime_customize", None)
+        except:
+            print(sys.version)
```
and it also gives python 3.10.8

**Comment by jgfouca** [comment]
Does the import work when you run from command line?

**Comment by jgfouca** [comment]
This is so strange, importlib.machinery has been in python3 for ages. It seems like you must somehow be getting moved to an older version during the execution of CIME.

**Comment by jedwards4b** [comment]
So I added print(sys.path) at the beginning of create_test
and in config.py,
These are present at the beginning but not at the error point:
```

 ['/glade/work/jedwards/sandboxes/EarthWorks/cime/../cime_config',                                            
'/glade/u/apps/cseg/python/lib64/python3.6/site-packages',                                                   
'/glade/u/apps/opt/conda/ncarbin/monitor/site-packages', ]            
```

**Comment by jgfouca** [comment]
Ok, I guess that is probably it. I do see a couple references to PYTHONPATH in test_scheduler. Specifically this one:
```
    ###########################################################################                                                                                                                                                 
    def _shell_cmd_for_phase(self, test, cmd, phase, from_dir=None):
        ###########################################################################                                                                                                                                             
        env = os.environ.copy()
        env["PYTHONPATH"] = f"{get_cime_root()}:{get_tools_path()}"
```

which would impact the PYTHONPATH for create_newcase.

**Comment by jgfouca** [comment]
I'm wondering why this PYTHONPATH totally ignores the existing PYTHONPATH?

**Comment by jedwards4b** [comment]
I changed that line:
```
-        env["PYTHONPATH"] = f"{get_cime_root()}:{get_tools_path()}"
+        pypath = env["PYTHONPATH"]
+        env["PYTHONPATH"] = f"{pypath}:{get_cime_root()}:{get_tools_path()}"

```
but it doesn't help.  So I tried:
```
diff --git a/CIME/test_scheduler.py b/CIME/test_scheduler.py
index d46d9e0d3..7ebdc1ed9 100644
--- a/CIME/test_scheduler.py
+++ b/CIME/test_scheduler.py
@@ -571,7 +571,8 @@ class TestScheduler(object):
     def _shell_cmd_for_phase(self, test, cmd, phase, from_dir=None):
         ###########################################################################
         env = os.environ.copy()
-        env["PYTHONPATH"] = f"{get_cime_root()}:{get_tools_path()}"
+        
+        env["PYTHONPATH"] = f"{sys.path}:{get_cime_root()}:{get_tools_path()}"
 
         while True:
             rc, output, errput = run_cmd(cmd, from_dir=from_dir, env=env)
@@ -983,7 +984,7 @@ class TestScheduler(object):
         # It's OK for this command to fail with baseline diffs but not catastrophically
         if rv[0]:
             env = os.environ.copy()
-            env["PYTHONPATH"] = f"{get_cime_root()}:{get_tools_path()}"
+            env["PYTHONPATH"] = f"{sys.path}:{get_cime_root()}:{get_tools_path()}"
             cmdstat, output, _ = run_cmd(
                 "./case.cmpgen_namelists",
                 combine_output=True,
```
but I still get the error.  I added some print statements - I'm not entering either of these code blocks.

**Comment by jedwards4b** [comment]
I've added a print in test_scheduler.py in _shell_command_for_phase
and another in the top of create_newcase.py
This is where the path is being changed.
```
Starting CREATE_NEWCASE for test SMS.mpasa120_mpasa120.FHS94.gust_nvhpc with 1 procs
shell cmd for phase/glade/work/jedwards/sandboxes/EarthWorks/cime/../cime_config
/glade/work/jedwards/sandboxes/EarthWorks/cime
/glade/work/jedwards/sandboxes/EarthWorks/cime
/glade/work/jedwards/sandboxes/EarthWorks/cime/CIME/Tools
/glade/work/jedwards/sandboxes/EarthWorks/cime/scripts
/glade/u/apps/cseg/python/lib64/python3.6/site-packages
/glade/u/apps/opt/conda/ncarbin/monitor/site-packages
/glade/work/jedwards/sandboxes/EarthWorks/cime/scripts
/glade/u/apps/gust/23.04/._opt/ps4ha333cxsfn2ycd6q2bpcgai36mblv/lib/python310.zip
/glade/u/apps/gust/23.04/._opt/ps4ha333cxsfn2ycd6q2bpcgai36mblv/lib/python3.10
/glade/u/apps/gust/23.04/._opt/ps4ha333cxsfn2ycd6q2bpcgai36mblv/lib/python3.10/lib-dynload
/glade/u/apps/gust/23.04/._opt/ps4ha333cxsfn2ycd6q2bpcgai36mblv/lib/python3.10/site-packages
/glade/work/jedwards/sandboxes/EarthWorks/cime
RUN: /glade/u/apps/gust/23.04/opt/bin/python3 /glade/work/jedwards/sandboxes/EarthWorks/cime/CIME/scripts/create_newcase.py --case /glade/gust/scratch/jedwards/SMS.mpasa120_mpasa120.FHS94.gust_nvhpc.20230504_133059_p2j2ou --res mpasa120_mpasa120 --compset FHS94 --test --machine gust --compiler nvhpc --project P93300606  --workflow default --srcroot /glade/work/jedwards/sandboxes/EarthWorks
FROM: /glade/work/jedwards/sandboxes/EarthWorks/cime/scripts
  stat: 1

  output: Top of create_newcase: /glade/work/jedwards/sandboxes/EarthWorks/cime
/glade/work/jedwards/sandboxes/EarthWorks/cime/CIME/scripts
/glade/work/jedwards/sandboxes/EarthWorks/cime
/glade/work/jedwards/sandboxes/EarthWorks/cime/CIME/Tools
/glade/u/apps/gust/23.04/._opt/ps4ha333cxsfn2ycd6q2bpcgai36mblv/lib/python310.zip
/glade/u/apps/gust/23.04/._opt/ps4ha333cxsfn2ycd6q2bpcgai36mblv/lib/python3.10
/glade/u/apps/gust/23.04/._opt/ps4ha333cxsfn2ycd6q2bpcgai36mblv/lib/python3.10/lib-dynload
/glade/u/apps/gust/23.04/._opt/ps4ha333cxsfn2ycd6q2bpcgai36mblv/lib/python3.10/site-packages
/glade/work/jedwards/sandboxes/EarthWorks/cime
 
```

**Comment by jgfouca** [comment]
OK, so test_scheduler is adding stuff to the PYTHONPATH that is breaking things?

**Comment by jgfouca** [comment]
These added paths are suspect:
```
/glade/u/apps/cseg/python/lib64/python3.6/site-packages
/glade/u/apps/opt/conda/ncarbin/monitor/site-packages
```

**Comment by jedwards4b** [comment]
But these were removed before the error occurs.  The importlib in question is in /glade/u/apps/gust/23.04/._opt/ps4ha333cxsfn2ycd6q2bpcgai36mblv/lib/python3.10/importlib
and I do see that path in sys.path at the point that the error occurs.

**Comment by jgfouca** [comment]
can you try this:

```
% export PYTHONPATH=/glade/work/jedwards/sandboxes/EarthWorks/cime/../cime_config:
/glade/work/jedwards/sandboxes/EarthWorks/cime:
/glade/work/jedwards/sandboxes/EarthWorks/cime:
/glade/work/jedwards/sandboxes/EarthWorks/cime/CIME/Tools:
/glade/work/jedwards/sandboxes/EarthWorks/cime/scripts:
/glade/u/apps/cseg/python/lib64/python3.6/site-packages:
/glade/u/apps/opt/conda/ncarbin/monitor/site-packages:
/glade/work/jedwards/sandboxes/EarthWorks/cime/scripts:
/glade/u/apps/gust/23.04/._opt/ps4ha333cxsfn2ycd6q2bpcgai36mblv/lib/python310.zip:
/glade/u/apps/gust/23.04/._opt/ps4ha333cxsfn2ycd6q2bpcgai36mblv/lib/python3.10:
/glade/u/apps/gust/23.04/._opt/ps4ha333cxsfn2ycd6q2bpcgai36mblv/lib/python3.10/lib-dynload:
/glade/u/apps/gust/23.04/._opt/ps4ha333cxsfn2ycd6q2bpcgai36mblv/lib/python3.10/site-packages:
/glade/work/jedwards/sandboxes/EarthWorks/cime

% python3
>>> import importlib
>>> importlib.machinery
```

**Comment by jedwards4b** [comment]
works:
```
python3
Python 3.10.8 (main, Mar 30 2023, 09:45:03) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib
>>> importlib.machinery
<module 'importlib.machinery' from '/glade/u/apps/gust/23.04/._opt/ps4ha333cxsfn2ycd6q2bpcgai36mblv/lib/python3.10/importlib/machinery.py'>
>>> 

```

**Comment by jedwards4b** [comment]
still works

**Comment by jgfouca** [comment]
can you confirm in the test script that sys.path is what you think it is? If so, I'm stumped.

**Comment by jgfouca** [comment]
@jasonb5 , any ideas?

**Comment by billsacks** [comment]
I was able to reproduce this error with CESM master when changing two externals to match what @jedwards4b is using:
- cime6.0.75 (rather than cime6.0.105)
- ccs_config_cesm0.0.69 (rather than ccs_config_cesm0.0.67)

When I switched back to cime6.0.105, this error went away. @jedwards4b is it feasible for you to update to the latest CIME?

**Comment by jedwards4b** [comment]
Updating to the latest cime solves the issue.
