### ISSUE TITLE
CIME 6.1.9 6.1.10 (current master) failing test_d_create_clone_new_user

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#4662]
(test_sys_create_newcase.TestCreateNewcase) ... FAIL
Tested on derecho and github workflow.

**Comment by jedwards4b** [comment]
```
======================================================================
FAIL: test_d_create_clone_new_user (test_sys_create_newcase.TestCreateNewcase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/work/jedwards/sandboxes/cesm3_0_x/cime/CIME/tests/test_sys_create_newcase.py", line 264, in test_d_create_clone_new_user
    self.run_cmd_assert_result(
  File "/glade/work/jedwards/sandboxes/cesm3_0_x/cime/CIME/tests/base.py", line 142, in run_cmd_assert_result
    self.assertEqual(stat, expected_stat, msg=msg)
AssertionError: 1 != 0 : 
    COMMAND: ./xmlchange CIME_OUTPUT_ROOT=/glade/derecho/scratch/this_is_not_a_user/scripts_regression_test.20240813_070745/TestCreateNewcase
    FROM_DIR: /glade/derecho/scratch/jedwards/scripts_regression_test.20240813_070745/TestCreateNewcase/testcreatenewcase
    SHOULD HAVE WORKED, INSTEAD GOT STAT 1
    OUTPUT: 
    ERRPUT: Detected diff in locked file 'env_build.xml'
	'CIME_OUTPUT_ROOT' has changed from '/glade/derecho/scratch/jedwards/scripts_regression_test.20240813_070745/TestCreateNewcase' to '/glade/derecho/scratch/this_is_not_a_user/scripts_regression_test.20240813_070745/TestCreateNewcase'
ERROR: For your changes to take effect, run:
./case.build --clean-all
./case.build
```

**Comment by jedwards4b** [comment]
Passes in cime6.1.1 fails in 6.1.2.   @jgfouca Can you have a look? 
```
commit 783f23a5775ca7b11335d460044388b9408ed663 (HEAD, tag: cime6.1.2, feature/github_interface)
Merge: ca6c0cdc7 2fb1de215
Author: James Foucar <jgfouca@sandia.gov>
Date:   Thu Jul 11 11:32:57 2024 -0600

    Merge pull request #4650 from ESMCI/fix-xmlchange
    
    Fixes check_lockedfiles call in xmlchange
    
    Fixes check_lockedfiles only being called once when multiple settings
    are changed.

```

**Comment by jgfouca** [comment]
@jedwards4b , I believe that was @jasonb5 's PR, I just merged it. I'll let him look at it unless he wants me to do it.
