### ISSUE TITLE
"GET_REFCASE=.TRUE." caused the branch run to fail

### ISSUE THREAD

**Issue by minxu74** [ESMCI/cime#4697]
When setting up a branch run and "GET_REFCASE=.TRUE.",  the branch run will fail with the following errors:

```
Traceback (most recent call last):
  File "/var/spool/slurmd/job32019842/slurm_script", line 82, in <module>
    _main_func(__doc__)
  File "/var/spool/slurmd/job32019842/slurm_script", line 77, in _main_func
    success = case.case_run(skip_pnl=skip_pnl, set_continue_run=set_continue_run, submit_resubmits=resubmit)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/u2/m/minxu/MyGit/e3sm_v3/cime/CIME/case/case_run.py", line 498, in case_run
    lid = _run_model(self, lid, skip_pnl, da_cycle=cycle)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/u2/m/minxu/MyGit/e3sm_v3/cime/CIME/case/case_run.py", line 290, in _run_model
    return run_and_log_case_status(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/u2/m/minxu/MyGit/e3sm_v3/cime/CIME/status.py", line 88, in run_and_log_case_status
    rv = func()
         ^^^^^^
  File "/global/u2/m/minxu/MyGit/e3sm_v3/cime/CIME/case/case_run.py", line 281, in <lambda>
    functor = lambda: _run_model_impl(case, lid, skip_pnl=skip_pnl, da_cycle=da_cycle)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/u2/m/minxu/MyGit/e3sm_v3/cime/CIME/case/case_run.py", line 108, in _run_model_impl
    _pre_run_check(case, lid, skip_pnl=skip_pnl, da_cycle=da_cycle)
  File "/global/u2/m/minxu/MyGit/e3sm_v3/cime/CIME/case/case_run.py", line 62, in _pre_run_check
    shutil.rmtree(os.path.join(rundir, "timing"))
  File "/global/common/software/nersc/pe/conda-envs/24.1.0/python-3.11/nersc-python/lib/python3.11/shutil.py", line 744, in rmtree
    onerror(os.path.islink, path, sys.exc_info())
  File "/global/common/software/nersc/pe/conda-envs/24.1.0/python-3.11/nersc-python/lib/python3.11/shutil.py", line 742, in rmtree
    raise OSError("Cannot call rmtree on a symbolic link")
OSError: Cannot call rmtree on a symbolic link
```
The reason is that the function `stage_refcase` will symbolically link all files in the refcase directory to the branch run directory including "timing" and "spio_stats" (maybe only used by E3SM), but in the `case_run.py`, it uses the python shutil tool `rmtree` to remove the above two symbolic links, which is not allowed by python. The simple solution is to add a condition in stage_refcase function to skipping linking these two files.  I will try to create a PR to have this easy fixes if the solution is workable.

**Comment by jasonb5** [comment]
@minxu74 Thanks for the fix.
