### ISSUE TITLE
inputdata download error 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#568]
When inputdata is missing on a local machine it appears that cime will download the
data correctly but exit with an error anyway:
```
ERROR: Failed to download input data
Traceback (most recent call last):
  File "/picnic/u/home/jedwards/cesm2_0_alpha/cime/scripts/Tools/../../utils/python/CIME/SystemTests/system_tests_common.py", line 90, in build
    model_only=(phase_name==MODEL_BUILD_PHASE))
  File "/picnic/u/home/jedwards/cesm2_0_alpha/cime/scripts/Tools/../../utils/python/CIME/SystemTests/system_tests_common.py", line 114, in build_phase
    self.build_indv(sharedlib_only=sharedlib_only, model_only=model_only)
  File "/picnic/u/home/jedwards/cesm2_0_alpha/cime/scripts/Tools/../../utils/python/CIME/SystemTests/system_tests_common.py", line 121, in build_indv
    sharedlib_only=sharedlib_only, model_only=model_only)
  File "/picnic/u/home/jedwards/cesm2_0_alpha/cime/scripts/Tools/../../utils/python/CIME/build.py", line 169, in case_build
    check_all_input_data(case)
  File "/picnic/u/home/jedwards/cesm2_0_alpha/cime/scripts/Tools/../../utils/python/CIME/build.py", line 322, in check_all_input_data
    expect(success, "Failed to download input data")
  File "/picnic/u/home/jedwards/cesm2_0_alpha/cime/scripts/Tools/../../utils/python/CIME/utils.py", line 26, in expect
    raise exc_type("ERROR: %s" % error_msg)
SystemExit: ERROR: Failed to download input data
```
This is an exit in the build phase - going to the case directory and reissuing the case.build sometimes works correctly but I've also noticed that file permissions in downloaded files may look pretty screwy - for example in a recent case the directory inputdata/atm/cam/ozone did not have the executable bit on and so access below that directory was failing.

**Comment by rljacob** [comment]
When making a branch to fix this, please start from the cime5.1.1 tag so the fix can be merge to master and cime5.1.
