### ISSUE TITLE
config_pes_converter.py not liking some XML comments

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#792]
Comments like this in the current ACME cime2 config_pesall.xml:

```
<!-------------------------------------------------------------------------------
  tasks/thread setup - GRID for one grid (not a pair of grids)
 ------------------------------------------------------------------------------->
```

Are generating errors like:
blogin1[97]: ./config_pes_converter.py -cime2file /lcrc/group/earthscience/jacob/ACMEpure/cime/machines-acme/config_pes.xml -cime4file ../../cime_config/acme/allactive/config_pesall.xml
```
Traceback (most recent call last):
  File "./config_pes_converter.py", line 266, in <module>
    pes_compare()
  File "./config_pes_converter.py", line 258, in pes_compare
    cime2pestree = PesTree(cime2file)
  File "/lcrc/group/earthscience/jacob/cimeESMCI/scripts/Tools/grid_xml_converter.py", line 261, in __init__
    self.doc = ET.parse(xmlfilename)
  File "/soft/python/2.7.6/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/soft/python/2.7.6/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/soft/python/2.7.6/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/soft/python/2.7.6/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 244, column 6
Exit 1
```

**Comment by rljacob** [comment]
I removed all the offending comment lines and got a different error:

```
  File "./config_pes_converter.py", line 266, in <module>
    pes_compare()
  File "./config_pes_converter.py", line 258, in pes_compare
    cime2pestree = PesTree(cime2file)
  File "/lcrc/group/earthscience/jacob/cimeESMCI/scripts/Tools/grid_xml_converter.py", line 266, in __init__
    self.populate()
  File "./config_pes_converter.py", line 187, in populate
    if not datanode.ignore:
AttributeError: 'Cime2PesNode' object has no attribute 'ignore'
```
Not sure what to do about that one.
