### ISSUE TITLE
Clearer error message needed for incorrect setting of CIME_MODEL

### ISSUE THREAD

**Issue by mvertens** [ESMCI/cime#860]
1) setenv  CIME_MODEL CESM,  results in following error message that is less than helpful
```
Traceback (most recent call last):
  File "./create_newcase", line 180, in <module>
    _main_func()
  File "./create_newcase", line 151, in _main_func
    with Case(caseroot, read_only=False) as case:
  File "/fs/cgd/data0/mvertens/src/cime.esmci/scripts/Tools/../../utils/python/CIME/case.py", line 77, in __init__
    self.read_xml()
  File "/fs/cgd/data0/mvertens/src/cime.esmci/scripts/Tools/../../utils/python/CIME/case.py", line 152, in read_xml
    self._env_entryid_files.append(EnvRun(self._caseroot))
  File "/fs/cgd/data0/mvertens/src/cime.esmci/scripts/Tools/../../utils/python/CIME/XML/env_run.py", line 16, in __init__
    EnvBase.__init__(self, case_root, infile)
  File "/fs/cgd/data0/mvertens/src/cime.esmci/scripts/Tools/../../utils/python/CIME/XML/env_base.py", line 25, in __init__
    headernode = headerobj.get_header_node(os.path.basename(fullpath))
  File "/fs/cgd/data0/mvertens/src/cime.esmci/scripts/Tools/../../utils/python/CIME/XML/headers.py", line 26, in get_header_node
    fnode = self.get_node("file", attributes={"name" : fname})
  File "/fs/cgd/data0/mvertens/src/cime.esmci/scripts/Tools/../../utils/python/CIME/XML/generic_xml.py", line 95, in get_node
    nodes = self.get_nodes(nodename, attributes=attributes, root=root, xpath=xpath)
  File "/fs/cgd/data0/mvertens/src/cime.esmci/scripts/Tools/../../utils/python/CIME/XML/generic_xml.py", line 118, in get_nodes
    root = self.root
AttributeError: 'Headers' object has no attribute 'root'
/

```
We need an error message saying what the acceptable values of CIME_MODEL currently are

2) If a try to invoked create_newcase for a CESM machine, but have not set CIME_MODEL to cesm,
a more clear error message would be helpful, stating that the machine is not available for the target CIME_MODEL and giving the supported CIME_MODELS that can be used.

**Comment by billsacks** [comment]
@mvertens and @fischer-ncar - is this still an issue? If so, should it be added to the cesm2 milestone?

**Comment by fischer-ncar** [comment]
Still an issue.  setenv CIME_MODEL CESM, now results in
ERROR: Could not find or open file /home/fischer/code/cesm2_0_alpha06n/cime/config/CESM/config_files.xml
